'use strict';

/**
 * FinTrace NCRP — investigation PDF dossier generator.
 *
 * Assembles a professional, multi-page (10+) PDF from a report's analysis
 * bundle using PDFKit. No chart rasterization happens here (that would pull in
 * canvas/puppeteer) — instead every visual is rendered as a full data table,
 * and a one-line pointer tells the reader to open the dashboard for charts.
 *
 * Sections, each starting on its own page:
 *    1. Cover                — case title, date, headline numbers, sign-off.
 *    2. Executive Summary    — key figures in a two-column table.
 *    3. Investigation Roadmap— prioritised P0–P3 action table.
 *    4. Layer Analysis       — per-layer aggregates.
 *    5. Money Flow Network   — heaviest account→account edges.
 *    6. Top Mule Accounts    — top 10 by score, with risk band.
 *    7. Lien Worksheet       — recoverable amounts per account.
 *    8. Cashout Analysis     — ATM hotspots, same-day cashouts, state spread.
 *    9. Geographic Hotspots  — cashout by state + top POS merchants.
 *   10. Timeline             — daily money movement.
 *   11. Key Findings         — the analyzer's auto-generated action list.
 *   12. Draft Emails         — every per-bank lien letter, copy-paste ready.
 * Every page carries the footer "Generated by FinTrace NCRP | MINT" + page x/N.
 *
 * Amounts use an ASCII "Rs." prefix rather than the ₹ glyph, which is absent
 * from PDFKit's built-in (WinAnsi) Helvetica and would otherwise render blank.
 *
 * @module backend/src/utils/pdfGenerator
 */

const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

// ─── Palette + layout constants ──────────────────────────────────────

const NAVY = '#1f3a5f';
const NAVY_LIGHT = '#33567f';
const INK = '#222222';
const MUTED = '#6b7785';
const ZEBRA = '#eef2f7';
const BORDER = '#cfd8e3';
const RISK_COLOR = Object.freeze({ HIGH: '#b00020', MEDIUM: '#b26a00', LOW: '#2e7d32' });
// Roadmap priority → text colour + printable severity label (red/amber/blue/grey).
const PRIORITY_COLOR = Object.freeze({ P0: '#b00020', P1: '#b26a00', P2: '#1565c0', P3: '#6b7785' });
const PRIORITY_LABEL = Object.freeze({ P0: 'P0 Critical', P1: 'P1 High', P2: 'P2 Medium', P3: 'P3 Low' });

const PAGE_MARGIN = 50;
const BRAND_FOOTER = 'Generated by FinTrace NCRP | MINT';

// ─── Number / date formatting ────────────────────────────────────────

/** @param {unknown} v */
function num(v) {
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : 0;
}

/**
 * The confirmed cash-out figure the dossier prints. Reads the single source of
 * truth (`summary.cashed_out`, the capped policy figure), falling back to the
 * cash-out view for analyses produced before that field existed.
 *
 * @param {Record<string, unknown>} summary
 * @param {Record<string, unknown>} cashout
 * @returns {number}
 */
function cashedOutForDisplay(summary = {}, cashout = {}) {
  return summary.cashed_out != null ? num(summary.cashed_out) : num(cashout.total_cashout_amount);
}

/**
 * Rupee amount with Indian digit grouping and an ASCII "Rs." prefix.
 * @param {unknown} value
 * @returns {string}
 */
function formatMoney(value) {
  const v = num(value);
  const neg = v < 0;
  const [intPart, decPart] = Math.abs(v).toFixed(2).split('.');
  let last3 = intPart.slice(-3);
  const rest = intPart.slice(0, -3);
  if (rest !== '') last3 = ',' + last3;
  const grouped = rest.replace(/\B(?=(\d{2})+(?!\d))/g, ',') + last3;
  return `${neg ? '-' : ''}Rs. ${grouped}.${decPart}`;
}

/** Integer with Indian grouping (counts). @param {unknown} value */
function formatCount(value) {
  return num(value).toLocaleString('en-IN');
}

/** "DD Mon YYYY" in UTC, or an em dash. @param {unknown} iso */
function formatDate(iso) {
  if (iso === null || iso === undefined || iso === '') return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${String(d.getUTCDate()).padStart(2, '0')} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
}

/** Mask all but the last 4 chars of an account number. @param {unknown} acc */
function maskAccount(acc) {
  const s = String(acc ?? '').trim();
  if (s.length <= 4) return s || '—';
  return `${'X'.repeat(Math.min(6, s.length - 4))}${s.slice(-4)}`;
}

/**
 * Replace glyphs absent from PDFKit's built-in WinAnsi Helvetica (which render
 * as blank boxes) with ASCII equivalents. The analyzer embeds ₹, ≥, →, and
 * smart quotes in human-readable roadmap/finding text; this keeps them legible.
 *
 * @param {unknown} v
 * @returns {string}
 */
function asciiSafe(v) {
  return String(v ?? '')
    .replace(/₹\s?/g, 'Rs. ')          // ₹ (rupee sign)
    .replace(/≥/g, '>=')                // ≥
    .replace(/≤/g, '<=')                // ≤
    .replace(/→/g, '->')                // →
    .replace(/[‘’‚]/g, "'")   // ‘ ’ ‚  → '
    .replace(/[“”„]/g, '"')   // “ ” „  → "
    .replace(/…/g, '...')               // … (horizontal ellipsis)
    .replace(/[–—−]/g, '-');       // – (en) — (em) − (U+2212 minus) → ASCII hyphen-minus
}

// ─── Low-level drawing helpers ───────────────────────────────────────

/** Usable content width between margins. @param {PDFKit.PDFDocument} doc */
function contentWidth(doc) {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

/**
 * Section heading with an accent underline. Resets the cursor to the left
 * margin and leaves a sensible gap before the body.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 */
function sectionHeading(doc, title) {
  const left = doc.page.margins.left;
  doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(15).text(title, left, doc.y);
  const y = doc.y + 3;
  doc.moveTo(left, y).lineTo(doc.page.width - doc.page.margins.right, y)
    .lineWidth(1.5).strokeColor(NAVY).stroke();
  doc.moveDown(0.9);
  doc.x = left;
  doc.fillColor(INK).font('Helvetica').fontSize(10);
}

/**
 * Body paragraph at full content width from the left margin.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} text
 * @param {{ gap?: number, size?: number, color?: string, bold?: boolean }} [opts]
 */
function para(doc, text, opts = {}) {
  const left = doc.page.margins.left;
  doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica')
    .fontSize(opts.size ?? 10)
    .fillColor(opts.color ?? INK)
    .text(text, left, doc.y, { width: contentWidth(doc), align: 'left' });
  if (opts.gap !== 0) doc.moveDown(opts.gap ?? 0.5);
  doc.x = left;
}

/**
 * Render a bordered, zebra-striped table that paginates itself, redrawing the
 * header row at the top of each continuation page.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{
 *   columns: Array<{ label: string, width: number, align?: 'left'|'right'|'center' }>,
 *   rows: Array<Array<string|number>>,
 *   fontSize?: number,
 *   rowColors?: Array<string|null>,
 * }} spec - `rowColors[i]`, when set, tints that row's text (overrides zebra text).
 */
function drawTable(doc, { columns, rows, fontSize = 9, rowColors = [] }) {
  const startX = doc.page.margins.left;
  const padH = 5;
  const padV = 5;
  const totalWidth = columns.reduce((s, c) => s + c.width, 0);

  const measure = (cells, bold) => {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(fontSize);
    let max = 0;
    for (let i = 0; i < columns.length; i++) {
      const h = doc.heightOfString(String(cells[i] ?? ''), {
        width: columns[i].width - padH * 2,
        align: columns[i].align || 'left',
      });
      if (h > max) max = h;
    }
    return max + padV * 2;
  };

  const paint = (cells, top, height, { bold = false, fill = null, textColor = INK } = {}) => {
    if (fill) doc.rect(startX, top, totalWidth, height).fill(fill);
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(fontSize).fillColor(textColor);
    let cx = startX;
    for (let i = 0; i < columns.length; i++) {
      doc.text(String(cells[i] ?? ''), cx + padH, top + padV, {
        width: columns[i].width - padH * 2,
        align: columns[i].align || 'left',
        lineBreak: true,
      });
      cx += columns[i].width;
    }
    // Outer border + vertical separators.
    doc.lineWidth(0.5).strokeColor(BORDER).rect(startX, top, totalWidth, height).stroke();
    let vx = startX;
    for (let i = 0; i < columns.length - 1; i++) {
      vx += columns[i].width;
      doc.moveTo(vx, top).lineTo(vx, top + height).stroke();
    }
  };

  const headerCells = columns.map((c) => c.label);
  const drawHeader = () => {
    const h = measure(headerCells, true);
    paint(headerCells, doc.y, h, { bold: true, fill: NAVY, textColor: '#ffffff' });
    doc.y += h;
  };

  drawHeader();
  rows.forEach((cells, idx) => {
    const rowH = measure(cells, false);
    if (doc.y + rowH > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      drawHeader();
    }
    const zebra = idx % 2 === 1 ? ZEBRA : null;
    const textColor = rowColors[idx] || INK;
    paint(cells, doc.y, rowH, { fill: zebra, textColor });
    doc.y += rowH;
  });

  doc.x = doc.page.margins.left;
  doc.y += 10;
}

// ─── Section renderers ───────────────────────────────────────────────

/**
 * Cover page — full-bleed banner, headline figures, and a sign-off block.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{ ackNo: string, generatedStr: string, victimLoss: number,
 *   trailDisputed: number, totalTxns: number, totalLayers: number,
 *   fraudStart: string }} c
 */
function renderCover(doc, c) {
  const left = doc.page.margins.left;

  // Banner.
  doc.save();
  doc.rect(0, 0, doc.page.width, 150).fill(NAVY);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(28).text('FinTrace NCRP', left, 48);
  doc.font('Helvetica').fontSize(13)
    .text('Cyber Crime Financial Trail — Investigation Dossier', left, 92);
  doc.restore();

  doc.fillColor(INK).font('Helvetica-Bold').fontSize(20)
    .text('Investigation Report', left, 195);
  doc.moveDown(1.2);
  doc.x = left;

  drawTable(doc, {
    fontSize: 11,
    columns: [
      { label: 'Field', width: 200 },
      { label: 'Value', width: contentWidth(doc) - 200 },
    ],
    rows: [
      ['Case / Acknowledgement No.', c.ackNo],
      ['Report Generated', c.generatedStr],
      ['Fraud Trail Start Date', c.fraudStart],
      ['Victim Loss (Layer 1)', formatMoney(c.victimLoss)],
      ['Total Trail Disputed (all layers)', formatMoney(c.trailDisputed)],
      ['Total Transactions', formatCount(c.totalTxns)],
      ['Layers Detected', formatCount(c.totalLayers)],
    ],
  });

  doc.moveDown(2);
  doc.x = left;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(INK);
  const line = (label) => {
    doc.text(`${label}  `, left, doc.y, { continued: true })
      .font('Helvetica').fillColor(MUTED).text('______________________________________')
      .font('Helvetica-Bold').fillColor(INK);
    doc.moveDown(0.8);
  };
  doc.text('Prepared / reviewed by:', left, doc.y);
  doc.moveDown(0.8);
  line('Case Officer :');
  line('Designation  :');
  line('Signature    :');
  line('Date         :');

  doc.moveDown(1.5);
  doc.font('Helvetica-Oblique').fontSize(8.5).fillColor(MUTED).text(
    'CONFIDENTIAL — For official use only. This dossier is generated from an NCRP ' +
    'BankAction CompleteTrail export and is intended solely for authorised ' +
    'investigation and judicial proceedings.',
    left, doc.y, { width: contentWidth(doc) }
  );
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {object} a - The analysis bundle.
 * @param {Array<object>} liens
 */
function renderExecutiveSummary(doc, a, liens) {
  sectionHeading(doc, '2. Executive Summary');
  para(doc,
    'Key figures for this case at a glance. Detailed breakdowns follow in the ' +
    'subsequent sections.', { gap: 0.8 });

  const summary = a.summary || {};
  const cashout = a.cashout_analysis || {};
  const mules = a.mule_detection || [];
  const highMules = mules.filter((m) => m.risk_label === 'HIGH').length;
  // Two distinct figures — never conflate (see analyzer summary):
  //   • recoverableResidual: victim loss not yet cashed out / frozen / refunded.
  //   • lienTableTotal: Σ per-account lien-eligible balances (can exceed the loss).
  const recoverableResidual = num(summary.recoverable_residual);
  const lienTableTotal = num(summary.lien_table_total) || (liens || []).reduce(
    (s, l) => s + num(l.lien_amount ?? l.lien_eligible_amount), 0);
  const banks = new Set((liens || []).map((l) => l.bank_name).filter(Boolean)).size;
  const cashedOut = cashedOutForDisplay(summary, cashout);

  drawTable(doc, {
    fontSize: 10,
    columns: [
      { label: 'Metric', width: 300 },
      { label: 'Value', width: contentWidth(doc) - 300, align: 'right' },
    ],
    rows: [
      ['Total transactions analysed', formatCount(summary.total_transactions)],
      ['Victim loss (Layer 1)', formatMoney(summary.victim_loss_amount ?? summary.total_disputed_amount)],
      ['Total trail disputed (all layers)', formatMoney(summary.total_trail_disputed ?? summary.total_disputed_amount)],
      ['Layers in the money trail', formatCount(summary.total_layers)],
      ['Distinct beneficiary accounts', formatCount(summary.total_accounts)],
      ['Fraud trail start date', formatDate(summary.fraud_start_date)],
      ['Total confirmed cashed out (ATM/POS)', formatMoney(cashedOut)],
      ['Recoverable residual (loss - cashed out - on hold - refunded)', formatMoney(recoverableResidual)],
      ['Same-day ATM cashouts', formatCount(cashout.same_day_cashouts)],
      ['High-risk mule accounts', formatCount(highMules)],
      ['Accounts with lien-eligible balance', formatCount((liens || []).length)],
      ['Total lien-eligible balance across flagged accounts', formatMoney(lienTableTotal)],
      ['Banks to be contacted for lien', formatCount(banks)],
    ],
  });

  para(doc,
    'Recoverable residual is the share of the victim loss not yet cashed out, frozen, or refunded — ' +
    'it sums with those to 100% of the loss. The total lien-eligible balance is the per-account freezable ' +
    'sum and may exceed the victim loss because funds are re-counted as they traverse multiple layers.',
    { gap: 0.6, size: 8.5, color: MUTED });

  para(doc, 'Note: visual charts are available on the FinTrace dashboard. This ' +
    'PDF presents the complete underlying data as tables.',
    { gap: 0, size: 8.5, color: MUTED });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} roadmap */
function renderRoadmap(doc, roadmap) {
  sectionHeading(doc, '3. Investigation Roadmap');
  para(doc,
    'Prioritised actions for the investigating officer, ordered P0 (act now) ' +
    'through P3 (corroborating evidence). Row colour signals urgency: ' +
    'P0 red, P1 amber, P2 blue, P3 grey.', { gap: 0.8 });

  const list = Array.isArray(roadmap) ? roadmap : [];
  if (list.length === 0) {
    para(doc, 'No roadmap actions were generated for this case.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 9,
    rowColors: list.map((r) => PRIORITY_COLOR[r.priority] || INK),
    columns: [
      { label: 'Priority', width: 75, align: 'center' },
      { label: 'Action', width: 165 },
      { label: 'Description', width: contentWidth(doc) - 240 },
    ],
    rows: list.map((r) => [
      PRIORITY_LABEL[r.priority] || r.priority || '—',
      asciiSafe(r.title),
      asciiSafe(r.description),
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} layers */
function renderLayers(doc, layers) {
  sectionHeading(doc, '4. Layer-by-Layer Analysis');
  para(doc,
    'Each layer is one hop further from the victim. Funds typically fan out and ' +
    'speed up as they move outward toward cashout points.', { gap: 0.8 });

  if (!layers || layers.length === 0) {
    para(doc, 'No layer data available.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    columns: [
      { label: 'Layer', width: 55, align: 'center' },
      { label: 'Accounts', width: 70, align: 'right' },
      { label: 'Total Amount', width: 110, align: 'right' },
      { label: 'Disputed', width: 105, align: 'right' },
      { label: 'Cashouts', width: 70, align: 'right' },
      { label: 'Avg Fwd (hrs)', width: contentWidth(doc) - 410, align: 'right' },
    ],
    rows: layers.map((l) => [
      `L${l.layer_no}`,
      formatCount(l.account_count),
      formatMoney(l.total_amount),
      formatMoney(l.disputed_amount),
      formatCount(l.cashout_count),
      l.avg_forward_time_hours == null ? '—' : num(l.avg_forward_time_hours).toFixed(2),
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {object} network - money_flow_network. */
function renderMoneyFlow(doc, network) {
  sectionHeading(doc, '5. Money Flow Network');
  para(doc,
    'The heaviest account-to-account transfers in the trail (top 10 by amount), ' +
    'aggregated across every hop between each pair. Account numbers are masked.',
    { gap: 0.8 });

  const edges = (network && Array.isArray(network.top_edges))
    ? network.top_edges.slice(0, 10) : [];
  if (edges.length === 0) {
    para(doc, 'No account-to-account edges were derived for this case.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 8.5,
    columns: [
      { label: 'Source A/c (masked)', width: 100 },
      { label: 'Destination (masked)', width: 100 },
      { label: 'Amount', width: 95, align: 'right' },
      { label: 'Txns', width: 40, align: 'right' },
      { label: 'Layers', width: 45, align: 'center' },
      { label: 'Bank', width: contentWidth(doc) - 380 },
    ],
    rows: edges.map((e) => [
      maskAccount(e.source),
      maskAccount(e.destination),
      formatMoney(e.amount),
      formatCount(e.txn_count),
      e.layers == null || e.layers === '' ? '—' : String(e.layers),
      asciiSafe(e.banks) || '—',
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} mules */
function renderMules(doc, mules) {
  sectionHeading(doc, '6. Top Mule Accounts');
  para(doc,
    'Accounts ranked by mule risk score (higher = stronger mule indicators). ' +
    'HIGH-risk accounts are the priority targets for lien and KYC requests. ' +
    'Account numbers are masked for the report.',
    { gap: 0.8 });

  const top = (mules || []).slice(0, 10);
  if (top.length === 0) {
    para(doc, 'No mule accounts were scored.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 8.5,
    rowColors: top.map((m) => RISK_COLOR[m.risk_label] || INK),
    columns: [
      { label: '#', width: 24, align: 'center' },
      { label: 'Account (masked)', width: 95 },
      { label: 'Bank', width: 95 },
      { label: 'Layer', width: 42, align: 'center' },
      { label: 'Score', width: 42, align: 'right' },
      { label: 'Risk', width: 55, align: 'center' },
      { label: 'Received', width: contentWidth(doc) - 353, align: 'right' },
    ],
    rows: top.map((m, i) => [
      i + 1,
      maskAccount(m.account_no),
      m.bank_name || '—',
      m.layer_no == null ? '—' : `L${m.layer_no}`,
      formatCount(m.mule_score),
      m.risk_label || '—',
      formatMoney(m.total_received),
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} liens */
function renderLien(doc, liens) {
  sectionHeading(doc, '7. Lien-Eligible Amounts');
  para(doc,
    'Lien-eligible balance per account — disputed inflow not yet confirmed withdrawn ' +
    'as cash. Subject to the actual available balance confirmed by the bank.',
    { gap: 0.8 });

  if (!liens || liens.length === 0) {
    para(doc, 'No accounts currently carry a lien-eligible balance.', { color: MUTED });
    return;
  }

  const total = liens.reduce((s, l) => s + num(l.lien_amount ?? l.lien_eligible_amount), 0);
  drawTable(doc, {
    fontSize: 8.5,
    columns: [
      { label: '#', width: 24, align: 'center' },
      { label: 'Account (masked)', width: 100 },
      { label: 'Bank', width: 110 },
      { label: 'IFSC', width: 85 },
      { label: 'Status', width: 60, align: 'center' },
      { label: 'Lien Amount', width: contentWidth(doc) - 379, align: 'right' },
    ],
    rows: liens.map((l, i) => [
      i + 1,
      maskAccount(l.account_no),
      l.bank_name || '—',
      l.ifsc_code || '—',
      l.lien_status || 'pending',
      formatMoney(l.lien_amount ?? l.lien_eligible_amount),
    ]),
  });

  para(doc, `Total lien-eligible balance across ${formatCount(liens.length)} flagged account(s): ` +
    `${formatMoney(total)}.`, { bold: true, gap: 0.4 });
  para(doc,
    '(May exceed the victim loss as funds traverse multiple layers — this is the freezable ' +
    'per-account balance, not the recoverable residual reported in the Executive Summary.)',
    { gap: 0, size: 8, color: MUTED });
}

/** @param {PDFKit.PDFDocument} doc @param {object} cashout */
function renderCashout(doc, cashout) {
  sectionHeading(doc, '8. Cashout Analysis');
  const c = cashout || {};

  para(doc, `Total confirmed cashed out (ATM + POS): ${formatMoney(c.total_cashout_amount)} ` +
    `across ${formatCount(c.total_cashout_transactions)} transaction(s).`, { gap: 0.3 });
  para(doc, `Same-day ATM cashouts: ${formatCount(c.same_day_cashouts)}` +
    (c.fastest_cashout_hours != null
      ? `   |   Fastest cashout: ${num(c.fastest_cashout_hours).toFixed(2)} hours after victim debit.`
      : '.'), { gap: 0.9 });

  const atms = c.atm_cashouts || [];
  if (atms.length > 0) {
    para(doc, 'ATM withdrawal locations (highest value first):', { bold: true, gap: 0.5 });
    drawTable(doc, {
      fontSize: 8.5,
      columns: [
        { label: 'ATM ID', width: 80 },
        { label: 'Location', width: 150 },
        { label: 'City', width: 80 },
        { label: 'State', width: 80 },
        { label: 'Amount', width: contentWidth(doc) - 460, align: 'right' },
        { label: 'Hits', width: 30, align: 'right' },
      ],
      rows: atms.map((a) => [
        a.atm_id || '—',
        a.atm_location || '—',
        a.city || '—',
        a.state || '—',
        formatMoney(a.amount),
        formatCount(a.count),
      ]),
    });
  } else {
    para(doc, 'No ATM/POS cashouts were detected in this trail.', { color: MUTED, gap: 0.9 });
  }

  const byState = c.cashout_by_state || [];
  if (byState.length > 0) {
    para(doc, 'Cashout distribution by state:', { bold: true, gap: 0.5 });
    drawTable(doc, {
      fontSize: 9,
      columns: [
        { label: 'State', width: 220 },
        { label: 'Cashout Amount', width: 150, align: 'right' },
        { label: 'Count', width: contentWidth(doc) - 370, align: 'right' },
      ],
      rows: byState.map((s) => [s.state, formatMoney(s.amount), formatCount(s.count)]),
    });
  }
}

/** @param {PDFKit.PDFDocument} doc @param {object} geography */
function renderGeography(doc, geography) {
  sectionHeading(doc, '9. Geographic Hotspots');
  const g = geography || {};
  const byState = Array.isArray(g.by_state) ? g.by_state : [];
  const merchants = Array.isArray(g.top_merchants) ? g.top_merchants : [];

  para(doc, 'Where the cashed-out funds surfaced — by state, and by merchant ' +
    '(POS terminals). Useful for jurisdiction and on-ground follow-up.', { gap: 0.8 });

  para(doc, 'Cashout by state:', { bold: true, gap: 0.5 });
  if (byState.length > 0) {
    drawTable(doc, {
      fontSize: 9,
      columns: [
        { label: 'State', width: 200 },
        { label: 'Amount', width: 130, align: 'right' },
        { label: 'Txns', width: 70, align: 'right' },
        { label: 'Share %', width: contentWidth(doc) - 400, align: 'right' },
      ],
      rows: byState.map((s) => [
        asciiSafe(s.state) || '—',
        formatMoney(s.amount),
        formatCount(s.txn_count ?? s.count),
        `${num(s.pct).toFixed(1)}%`,
      ]),
    });
  } else {
    para(doc, 'No state-level location data was present in this NCRP export.',
      { color: MUTED, gap: 0.9 });
  }

  para(doc, 'Top merchants (POS cashouts):', { bold: true, gap: 0.5 });
  if (merchants.length > 0) {
    drawTable(doc, {
      fontSize: 9,
      columns: [
        { label: 'Merchant Name', width: 230 },
        { label: 'Type', width: 90 },
        { label: 'Amount', width: 110, align: 'right' },
        { label: 'Txns', width: contentWidth(doc) - 430, align: 'right' },
      ],
      rows: merchants.slice(0, 10).map((m) => [
        asciiSafe(m.name) || '—',
        asciiSafe(m.type) || 'Merchant',
        formatMoney(m.amount),
        formatCount(m.txn_count),
      ]),
    });
  } else {
    para(doc, 'No POS / merchant cashouts were detected in this trail.',
      { color: MUTED, gap: 0 });
  }
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} timeline */
function renderTimeline(doc, timeline) {
  sectionHeading(doc, '10. Timeline Summary');
  para(doc, 'Daily money movement across the fraud trail (IST calendar days).',
    { gap: 0.8 });

  if (!timeline || timeline.length === 0) {
    para(doc, 'No dated transactions available for a timeline.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    columns: [
      { label: 'Date', width: 160 },
      { label: 'Transactions', width: 130, align: 'right' },
      { label: 'Total Amount', width: contentWidth(doc) - 290, align: 'right' },
    ],
    rows: timeline.map((t) => [
      formatDate(t.date),
      formatCount(t.transaction_count),
      formatMoney(t.total_amount),
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {string[]} findings */
function renderFindings(doc, findings) {
  sectionHeading(doc, '11. Key Findings & Recommended Actions');

  const list = Array.isArray(findings) ? findings : [];
  if (list.length === 0) {
    para(doc, 'No automated findings were generated for this case.', { color: MUTED });
    return;
  }

  const left = doc.page.margins.left;
  list.forEach((f, i) => {
    if (doc.y + 40 > doc.page.height - doc.page.margins.bottom) doc.addPage();
    doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY_LIGHT)
      .text(`${i + 1}.`, left, doc.y, { width: 22, continued: false });
    doc.moveUp();
    doc.font('Helvetica').fontSize(10.5).fillColor(INK)
      .text(String(f), left + 22, doc.y, { width: contentWidth(doc) - 22 });
    doc.moveDown(0.6);
    doc.x = left;
  });
}

/**
 * Short, human label for a bank-attribution flag (used in the table column).
 * @param {string} flag
 */
function flagLabel(flag) {
  switch (flag) {
    case 'IFSC_TEXT_MISMATCH': return 'IFSC vs text';
    case 'NO_IFSC': return 'No IFSC';
    case 'INVALID_IFSC': return 'Invalid IFSC';
    case 'UNKNOWN_IFSC_PREFIX': return 'Unknown prefix';
    default: return flag || '—';
  }
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} dataQuality */
function renderDataQuality(doc, dataQuality) {
  const list = Array.isArray(dataQuality) ? dataQuality : [];
  doc.addPage();
  sectionHeading(doc, '12. Bank Attribution — Data Quality Review');

  if (list.length === 0) {
    para(doc,
      'Every account resolved cleanly: the bank name on each lien letter was ' +
      'derived from a valid IFSC that agreed with the source file. No accounts ' +
      'require manual bank verification.', { color: MUTED });
    return;
  }

  para(doc,
    `${formatCount(list.length)} account(s) below need the investigating officer to ` +
    'confirm the freeze target. The bank printed on each lien letter is taken from ' +
    "the account's IFSC (authoritative); where the source file's text disagreed or " +
    'no usable IFSC was present, it is listed here for review. The financial amounts ' +
    'are unaffected — only the bank attribution is flagged.', { gap: 0.8 });

  drawTable(doc, {
    fontSize: 8,
    columns: [
      { label: '#', width: 22, align: 'center' },
      { label: 'Account (masked)', width: 96 },
      { label: 'Resolved bank (letter)', width: 120 },
      { label: 'IFSC', width: 76 },
      { label: 'Flag', width: 64 },
      { label: 'Source-file text', width: contentWidth(doc) - 378 },
    ],
    rows: list.map((d, i) => [
      i + 1,
      maskAccount(d.account_no),
      d.bank || '—',
      d.ifsc_code || '—',
      flagLabel(d.bank_flag),
      d.raw_bank || '(blank)',
    ]),
  });

  para(doc,
    'Action: for "IFSC vs text" rows the letter already uses the IFSC-derived bank — ' +
    'verify and dispatch. For "No IFSC" / "Invalid IFSC" rows (wallets / PA / PG ids) ' +
    'confirm the correct nodal entity. For "Unknown prefix" rows the IFSC bank map ' +
    'should be extended.', { gap: 0, size: 8, color: MUTED });
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {Array<object>} emails
 * @param {Array<object>} [dataQuality] - flagged accounts, for per-letter notes
 */
function renderEmails(doc, emails, dataQuality) {
  const list = Array.isArray(emails) ? emails : [];
  // account_no -> flag, so each letter can footnote its flagged accounts.
  const flagByAccount = new Map(
    (Array.isArray(dataQuality) ? dataQuality : []).map((d) => [String(d.account_no), d.bank_flag]));
  doc.addPage();
  sectionHeading(doc, '13. Draft Lien-Request Emails');

  if (list.length === 0) {
    para(doc, 'No draft emails were generated (no lien-eligible accounts).',
      { color: MUTED });
    return;
  }

  para(doc,
    `${formatCount(list.length)} per-bank letter(s) below — copy the subject and ` +
    'body into your email client. Each cites Section 102 Cr.P.C. read with the IT ' +
    'Act, 2000.', { gap: 0.8 });

  const left = doc.page.margins.left;
  list.forEach((email, idx) => {
    if (idx > 0) doc.addPage();
    else if (doc.y + 120 > doc.page.height - doc.page.margins.bottom) doc.addPage();

    doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY)
      .text(`Letter ${idx + 1} of ${list.length} — ${email.bank_name || 'Unknown Bank'}`,
        left, doc.y, { width: contentWidth(doc) });
    doc.moveDown(0.4);
    doc.x = left;

    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(INK)
      .text('Subject: ', left, doc.y, { continued: true })
      .font('Helvetica').text(email.subject || '', { width: contentWidth(doc) });
    doc.moveDown(0.6);
    doc.x = left;

    // Body in a monospace font so the account table lines up; PDFKit flows it
    // across pages automatically.
    doc.font('Courier').fontSize(8.5).fillColor(INK)
      .text(email.body || '', left, doc.y, { width: contentWidth(doc), align: 'left' });
    doc.x = left;

    // Reviewer note (NOT part of the dispatched letter): flag any account in
    // this letter whose bank was derived from the IFSC over a differing source
    // text, so the officer verifies before sending.
    const flagged = (Array.isArray(email.account_list) ? email.account_list : [])
      .filter((acc) => flagByAccount.has(String(acc)));
    if (flagged.length) {
      doc.moveDown(0.6);
      doc.x = left;
      doc.font('Helvetica-Oblique').fontSize(7.5).fillColor(MUTED)
        .text(
          'Reviewer note (not part of the dispatched letter): bank derived from IFSC; ' +
          `source file text differed or carried no IFSC for account(s): ${flagged.map(maskAccount).join(', ')}. ` +
          'See section 12 (Data Quality).',
          left, doc.y, { width: contentWidth(doc) });
      doc.x = left;
    }
  });
}

// ─── Footer pass ─────────────────────────────────────────────────────

/**
 * Stamp every buffered page with the brand footer and "Page x of N".
 *
 * The footer sits below the content area, inside the bottom-margin band. Text
 * positioned there would normally make PDFKit auto-add a page (it thinks the
 * line doesn't fit), so the bottom margin is zeroed for the duration of each
 * write and then restored — the standard recipe for fixed footers.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function stampFooters(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);

    const restoreBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0; // suppress auto page-break in the footer band

    const left = doc.page.margins.left;
    const width = contentWidth(doc);
    const y = doc.page.height - 32;

    doc.moveTo(left, y - 6).lineTo(left + width, y - 6)
      .lineWidth(0.5).strokeColor(BORDER).stroke();
    doc.font('Helvetica').fontSize(8).fillColor(MUTED);
    doc.text(BRAND_FOOTER, left, y, { width, align: 'left', lineBreak: false });
    doc.text(`Page ${i + 1} of ${range.count}`, left, y, { width, align: 'right', lineBreak: false });

    doc.page.margins.bottom = restoreBottom;
  }
}

// ─── Public API ──────────────────────────────────────────────────────

/**
 * Generate the investigation PDF for one report and write it to `outputPath`.
 *
 * The promise resolves with `outputPath` once the file stream has fully
 * flushed, or rejects if PDFKit or the write stream errors. The parent
 * directory is created if missing.
 *
 * @param {{
 *   report?: Record<string, unknown>,
 *   analysis?: Record<string, unknown>,
 *   liens?: Array<Record<string, unknown>>,
 *   emails?: Array<Record<string, unknown>>,
 *   layers?: Array<Record<string, unknown>>,
 *   ack_no?: string|null,
 *   complaint_date?: string|null,
 * }} data - The report's analysis bundle (analysis = parsed analysis_json).
 * @param {string} outputPath - Absolute path of the .pdf to write.
 * @returns {Promise<string>} Resolves to `outputPath`.
 *
 * @example
 *   await generateReportPdf({ report, analysis, liens, emails, layers },
 *     path.join(exportsDir, 'FinTrace-NCRP123-1716800000000.pdf'));
 */
function generateReportPdf(data, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    } catch (err) {
      reject(new Error(`generateReportPdf: cannot create output directory: ${err.message}`));
      return;
    }

    const {
      report = {}, analysis = {}, liens = [], emails = [], layers = [],
    } = data || {};
    const summary = analysis.summary || {};
    // Prefer persisted layer rows; fall back to the analysis snapshot.
    const layerRows = (layers && layers.length) ? layers : (analysis.layer_analysis || []);
    const ackNo = (data && data.ack_no) || report.ack_no || `report-${report.id ?? '—'}`;

    const doc = new PDFDocument({
      size: 'A4',
      margin: PAGE_MARGIN,
      bufferPages: true,
      info: {
        Title: `FinTrace NCRP Investigation Report — ${ackNo}`,
        Author: 'FinTrace NCRP | MINT',
        Subject: 'Cyber Crime Financial Trail Analysis',
      },
    });

    const stream = fs.createWriteStream(outputPath);
    let settled = false;
    const fail = (err) => {
      if (settled) return;
      settled = true;
      reject(err instanceof Error ? err : new Error(String(err)));
    };
    stream.on('error', fail);
    doc.on('error', fail);
    stream.on('finish', () => {
      if (settled) return;
      settled = true;
      resolve(outputPath);
    });

    doc.pipe(stream);

    // Global glyph sanitizer: PDFKit's built-in WinAnsi Helvetica has no glyph
    // for U+2212, en/em dashes, smart quotes, ellipsis, ₹, ≥, etc. — they render
    // as blank boxes (a "−" shows as a stray double-quote). Route EVERY drawn
    // string and its layout measurement through asciiSafe so both agree, catching
    // table cells, headings, paragraphs, cover, footers, and the '—' fallbacks
    // that bypass the per-field asciiSafe() calls.
    const drawText = doc.text.bind(doc);
    doc.text = (str, ...rest) => drawText(asciiSafe(str), ...rest);
    const measureHeight = doc.heightOfString.bind(doc);
    doc.heightOfString = (str, ...rest) => measureHeight(asciiSafe(str), ...rest);

    try {
      // 1. Cover (current first page). Headline money figure is the Layer-1
      // victim loss (the actual amount stolen); the all-layers trail-disputed
      // figure re-counts the same money across hops and is shown beneath it.
      renderCover(doc, {
        ackNo: String(ackNo),
        generatedStr: formatDate(new Date().toISOString()),
        victimLoss: summary.victim_loss_amount
          ?? summary.total_disputed_amount ?? report.total_disputed_amount,
        trailDisputed: summary.total_trail_disputed
          ?? summary.total_disputed_amount ?? report.total_disputed_amount,
        totalTxns: summary.total_transactions ?? report.total_transactions,
        totalLayers: summary.total_layers ?? report.total_layers,
        fraudStart: formatDate(summary.fraud_start_date ?? report.fraud_start_date),
      });

      // 2-11. One section per page.
      doc.addPage(); renderExecutiveSummary(doc, analysis, liens);
      doc.addPage(); renderRoadmap(doc, analysis.investigation_roadmap || []);
      doc.addPage(); renderLayers(doc, layerRows);
      doc.addPage(); renderMoneyFlow(doc, analysis.money_flow_network || {});
      doc.addPage(); renderMules(doc, analysis.mule_detection || []);
      doc.addPage(); renderLien(doc, liens);
      doc.addPage(); renderCashout(doc, analysis.cashout_analysis || {});
      doc.addPage(); renderGeography(doc, analysis.geography || {});
      doc.addPage(); renderTimeline(doc, analysis.timeline || []);
      doc.addPage(); renderFindings(doc, analysis.key_findings || []);

      // 12. Bank-attribution data-quality review (adds its own page).
      renderDataQuality(doc, analysis.data_quality || []);

      // 13. Draft emails (adds its own pages). Pass the flagged accounts so each
      // letter can carry a reviewer note where its bank was IFSC-corrected.
      renderEmails(doc, emails, analysis.data_quality || []);

      // Footer + page numbers across every buffered page.
      stampFooters(doc);
    } catch (err) {
      fail(err);
      return;
    }

    doc.end();
  });
}

// ─── Exports ─────────────────────────────────────────────────────────

module.exports = {
  generateReportPdf,
  // Exposed for unit tests; not part of the stable contract.
  _internals: Object.freeze({
    formatMoney,
    formatCount,
    formatDate,
    maskAccount,
    cashedOutForDisplay,
  }),
};
