'use strict';

/**
 * FinTrace NCRP — investigation PDF dossier generator.
 *
 * Assembles a professional, multi-page PDF from a report's analysis bundle
 * using PDFKit. The dossier leads with a visual section — charts are built as
 * SVG and rasterised to PNG (see ./charts.js) for reliable printing — then
 * relegates the bulky data tables to a clearly labelled Annexure at the back.
 *
 * Front matter (one section per page):
 *    Cover                   — case title, date, headline numbers, sign-off.
 *    1. Executive Summary    — key figures in a two-column table.
 *    2. Visual Summary       — money-flow network, layer-breakdown, and daily-
 *                              volume charts (rasterised PNGs).
 *    3. Investigation Roadmap— prioritised P0–P3 action table.
 *    4. Key Findings         — the analyzer's auto-generated action list.
 * Annexure (supporting data tables, behind a divider page):
 *    A. Layer Analysis       — per-layer aggregates.
 *    B. Money Flow Network   — heaviest account→account edges.
 *    C. Top Mule Accounts    — top 10 by score, with risk band.
 *    D. Lien Worksheet       — recoverable amounts per account.
 *    E. Cashout Analysis     — ATM hotspots, same-day cashouts, state spread.
 *    F. Geographic Hotspots  — cashout by state + top POS merchants.
 *    G. Timeline             — daily money movement.
 *    H. Data Quality         — bank-attribution review.
 * Followed by: Draft Emails  — every per-bank lien letter, copy-paste ready.
 * Every page carries the footer "Generated by FinTrace NCRP | MINT" + page x/N.
 *
 * Amounts use an ASCII "Rs." prefix rather than the ₹ glyph, which is absent
 * from PDFKit's built-in (WinAnsi) Helvetica and would otherwise render blank.
 *
 * @module backend/src/utils/pdfGenerator
 */

const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const {
  posMerchantAggregates, atmOnlyCashouts, cashoutReconciliation,
} = require('./exportViews');
const { renderCharts } = require('./charts');
const { appVersion } = require('../lib/provenance');
const { buildEmailArtifacts, composeLetterText } = require('./emailGenerator');

// ─── Palette + layout constants ──────────────────────────────────────

const NAVY = '#1f3a5f';
const NAVY_LIGHT = '#33567f';
const INK = '#222222';
const MUTED = '#6b7785';
const ZEBRA = '#eef2f7';
const BORDER = '#cfd8e3';
const RISK_COLOR = Object.freeze({ HIGH: '#b00020', MEDIUM: '#b26a00', LOW: '#2e7d32' });
// Roadmap priority → text colour + printable severity label (red/amber/blue/grey).
const PRIORITY_COLOR = Object.freeze({ P0: '#b00020', P1: '#b26a00', P2: '#1565c0', P3: '#6b7785' });
const PRIORITY_LABEL = Object.freeze({ P0: 'P0 Critical', P1: 'P1 High', P2: 'P2 Medium', P3: 'P3 Low' });

const PAGE_MARGIN = 50;
const BRAND_FOOTER = 'Generated by FinTrace NCRP | MINT';

// ─── Number / date formatting ────────────────────────────────────────

/** @param {unknown} v */
function num(v) {
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : 0;
}

/**
 * The confirmed cash-out figure the dossier prints. Reads the single source of
 * truth (`summary.cashed_out`, the capped policy figure), falling back to the
 * cash-out view for analyses produced before that field existed.
 *
 * @param {Record<string, unknown>} summary
 * @param {Record<string, unknown>} cashout
 * @returns {number}
 */
function cashedOutForDisplay(summary = {}, cashout = {}) {
  return summary.cashed_out != null ? num(summary.cashed_out) : num(cashout.total_cashout_amount);
}

/**
 * Rupee amount with Indian digit grouping and an ASCII "Rs." prefix.
 * @param {unknown} value
 * @returns {string}
 */
function formatMoney(value) {
  const v = num(value);
  const neg = v < 0;
  const [intPart, decPart] = Math.abs(v).toFixed(2).split('.');
  let last3 = intPart.slice(-3);
  const rest = intPart.slice(0, -3);
  if (rest !== '') last3 = ',' + last3;
  const grouped = rest.replace(/\B(?=(\d{2})+(?!\d))/g, ',') + last3;
  return `${neg ? '-' : ''}Rs. ${grouped}.${decPart}`;
}

/** Integer with Indian grouping (counts). @param {unknown} value */
function formatCount(value) {
  return num(value).toLocaleString('en-IN');
}

/** "DD Mon YYYY" in UTC, or an em dash. @param {unknown} iso */
function formatDate(iso) {
  if (iso === null || iso === undefined || iso === '') return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${String(d.getUTCDate()).padStart(2, '0')} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
}

/**
 * Mask an account identifier for display.
 *
 * Bank account NUMBERS (all-digit) keep their last 4 digits behind a fixed-
 * length mask that never reveals the true length. Non-numeric identifiers (UPI
 * VPAs like "name@bank", wallet / PG / PA handles) are operational identifiers,
 * not account numbers: masking them to their last 4 chars collapses distinct
 * handles that share a bank suffix (e.g. "a@ptaxis" and "b@naviaxis" → both
 * "…axis"), hiding that they are different freeze-review targets. For those we
 * mask only long embedded digit runs (phone/account-like) and keep the
 * alphanumeric structure, so distinct handles never render identically.
 *
 * @param {unknown} acc
 */
function maskAccount(acc) {
  const s = String(acc ?? '').trim();
  if (s === '') return '—';
  if (/^\d+$/.test(s)) {
    if (s.length <= 4) return s;
    return `${'X'.repeat(Math.min(6, s.length - 4))}${s.slice(-4)}`;
  }
  return s.replace(/\d{5,}/g, (run) => `${'X'.repeat(Math.min(6, run.length - 4))}${run.slice(-4)}`);
}

/**
 * Replace glyphs absent from PDFKit's built-in WinAnsi Helvetica (which render
 * as blank boxes) with ASCII equivalents. The analyzer embeds ₹, ≥, →, and
 * smart quotes in human-readable roadmap/finding text; this keeps them legible.
 *
 * @param {unknown} v
 * @returns {string}
 */
function asciiSafe(v) {
  return String(v ?? '')
    .replace(/₹\s?/g, 'Rs. ')          // ₹ (rupee sign)
    .replace(/≥/g, '>=')                // ≥
    .replace(/≤/g, '<=')                // ≤
    .replace(/→/g, '->')                // →
    .replace(/[‘’‚]/g, "'")   // ‘ ’ ‚  → '
    .replace(/[“”„]/g, '"')   // “ ” „  → "
    .replace(/…/g, '...')               // … (horizontal ellipsis)
    .replace(/[–—−]/g, '-');       // – (en) — (em) − (U+2212 minus) → ASCII hyphen-minus
}

// ─── Low-level drawing helpers ───────────────────────────────────────

/** Usable content width between margins. @param {PDFKit.PDFDocument} doc */
function contentWidth(doc) {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

/**
 * Section heading with an accent underline. Resets the cursor to the left
 * margin and leaves a sensible gap before the body.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 */
function sectionHeading(doc, title) {
  const left = doc.page.margins.left;
  doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(15).text(title, left, doc.y);
  const y = doc.y + 3;
  doc.moveTo(left, y).lineTo(doc.page.width - doc.page.margins.right, y)
    .lineWidth(1.5).strokeColor(NAVY).stroke();
  doc.moveDown(0.9);
  doc.x = left;
  doc.fillColor(INK).font('Helvetica').fontSize(10);
}

/**
 * Body paragraph at full content width from the left margin.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} text
 * @param {{ gap?: number, size?: number, color?: string, bold?: boolean }} [opts]
 */
function para(doc, text, opts = {}) {
  const left = doc.page.margins.left;
  doc.font(opts.bold ? 'Helvetica-Bold' : 'Helvetica')
    .fontSize(opts.size ?? 10)
    .fillColor(opts.color ?? INK)
    .text(text, left, doc.y, { width: contentWidth(doc), align: 'left' });
  if (opts.gap !== 0) doc.moveDown(opts.gap ?? 0.5);
  doc.x = left;
}

/**
 * Render a bordered, zebra-striped table that paginates itself, redrawing the
 * header row at the top of each continuation page.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{
 *   columns: Array<{ label: string, width: number, align?: 'left'|'right'|'center' }>,
 *   rows: Array<Array<string|number>>,
 *   fontSize?: number,
 *   rowColors?: Array<string|null>,
 * }} spec - `rowColors[i]`, when set, tints that row's text (overrides zebra text).
 */
function drawTable(doc, { columns, rows, fontSize = 9, rowColors = [] }) {
  const startX = doc.page.margins.left;
  const padH = 5;
  const padV = 5;
  const totalWidth = columns.reduce((s, c) => s + c.width, 0);

  const measure = (cells, bold) => {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(fontSize);
    let max = 0;
    for (let i = 0; i < columns.length; i++) {
      const h = doc.heightOfString(String(cells[i] ?? ''), {
        width: columns[i].width - padH * 2,
        align: columns[i].align || 'left',
      });
      if (h > max) max = h;
    }
    return max + padV * 2;
  };

  const paint = (cells, top, height, { bold = false, fill = null, textColor = INK } = {}) => {
    if (fill) doc.rect(startX, top, totalWidth, height).fill(fill);
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(fontSize).fillColor(textColor);
    let cx = startX;
    for (let i = 0; i < columns.length; i++) {
      doc.text(String(cells[i] ?? ''), cx + padH, top + padV, {
        width: columns[i].width - padH * 2,
        align: columns[i].align || 'left',
        lineBreak: true,
      });
      cx += columns[i].width;
    }
    // Outer border + vertical separators.
    doc.lineWidth(0.5).strokeColor(BORDER).rect(startX, top, totalWidth, height).stroke();
    let vx = startX;
    for (let i = 0; i < columns.length - 1; i++) {
      vx += columns[i].width;
      doc.moveTo(vx, top).lineTo(vx, top + height).stroke();
    }
  };

  const headerCells = columns.map((c) => c.label);
  const drawHeader = () => {
    const h = measure(headerCells, true);
    paint(headerCells, doc.y, h, { bold: true, fill: NAVY, textColor: '#ffffff' });
    doc.y += h;
  };

  drawHeader();
  rows.forEach((cells, idx) => {
    const rowH = measure(cells, false);
    if (doc.y + rowH > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      drawHeader();
    }
    const zebra = idx % 2 === 1 ? ZEBRA : null;
    const textColor = rowColors[idx] || INK;
    paint(cells, doc.y, rowH, { fill: zebra, textColor });
    doc.y += rowH;
  });

  doc.x = doc.page.margins.left;
  doc.y += 10;
}

// ─── Section renderers ───────────────────────────────────────────────

/**
 * Cover page — full-bleed banner, headline figures, and a sign-off block.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{ ackNo: string, generatedStr: string, victimLoss: number,
 *   trailDisputed: number, totalTxns: number, totalLayers: number,
 *   fraudStart: string,
 *   provenance?: { sha256: string|null, filename: string|null,
 *     ingestedAt: string|null, version: string } }} c
 */
function renderCover(doc, c) {
  const left = doc.page.margins.left;

  // Banner.
  doc.save();
  doc.rect(0, 0, doc.page.width, 150).fill(NAVY);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(28).text('FinTrace NCRP', left, 48);
  doc.font('Helvetica').fontSize(13)
    .text('Cyber Crime Financial Trail — Investigation Dossier', left, 92);
  doc.restore();

  doc.fillColor(INK).font('Helvetica-Bold').fontSize(20)
    .text('Investigation Report', left, 195);
  doc.moveDown(1.2);
  doc.x = left;

  drawTable(doc, {
    fontSize: 11,
    columns: [
      { label: 'Field', width: 200 },
      { label: 'Value', width: contentWidth(doc) - 200 },
    ],
    rows: [
      ['Case / Acknowledgement No.', c.ackNo],
      ['Report Generated', c.generatedStr],
      ['Fraud Trail Start Date', c.fraudStart],
      ['Victim Loss (Layer 1)', formatMoney(c.victimLoss)],
      ['Total Trail Disputed (all layers)', formatMoney(c.trailDisputed)],
      ['Total Transactions', formatCount(c.totalTxns)],
      ['Layers Detected', formatCount(c.totalLayers)],
    ],
  });

  // ── Source & Provenance ─────────────────────────────────────────────
  // Court-grade traceability: the dossier is bound to the exact source file by
  // its SHA-256 (also stamped in every page footer + the PDF metadata).
  const prov = c.provenance || {};
  doc.moveDown(1.2);
  doc.x = left;
  doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(12)
    .text('Source & Provenance', left, doc.y);
  const ruleY = doc.y + 2;
  doc.moveTo(left, ruleY).lineTo(doc.page.width - doc.page.margins.right, ruleY)
    .lineWidth(1).strokeColor(NAVY).stroke();
  doc.moveDown(0.6);
  doc.x = left;

  const provRow = (label, value, mono) => {
    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(INK)
      .text(`${label}  `, left, doc.y, { continued: true, width: contentWidth(doc) })
      .font(mono ? 'Courier' : 'Helvetica').fillColor(INK)
      .text(String(value), { width: contentWidth(doc) });
    doc.moveDown(0.35);
    doc.x = left;
  };
  provRow('Source file:', prov.filename || 'Not recorded');
  provRow('Source SHA-256:', prov.sha256 || 'Not recorded (legacy report)', true);
  provRow('Ingested (UTC):', formatDate(prov.ingestedAt));
  provRow('FinTrace version:', prov.version || appVersion());
  doc.font('Helvetica-Oblique').fontSize(8).fillColor(MUTED).text(
    'The SHA-256 above is computed over the raw uploaded NCRP file before parsing. ' +
    'It is repeated in the footer of every page and embedded in this PDF\'s metadata, ' +
    'so any extracted page remains traceable to its source.',
    left, doc.y, { width: contentWidth(doc) });
  doc.x = left;

  doc.moveDown(1.4);
  doc.x = left;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(INK);
  const line = (label) => {
    doc.text(`${label}  `, left, doc.y, { continued: true })
      .font('Helvetica').fillColor(MUTED).text('______________________________________')
      .font('Helvetica-Bold').fillColor(INK);
    doc.moveDown(0.8);
  };
  doc.text('Prepared / reviewed by:', left, doc.y);
  doc.moveDown(0.8);
  line('Case Officer :');
  line('Designation  :');
  line('Signature    :');
  line('Date         :');

  doc.moveDown(1.5);
  doc.font('Helvetica-Oblique').fontSize(8.5).fillColor(MUTED).text(
    'CONFIDENTIAL — For official use only. This dossier is generated from an NCRP ' +
    'BankAction CompleteTrail export and is intended solely for authorised ' +
    'investigation and judicial proceedings.',
    left, doc.y, { width: contentWidth(doc) }
  );
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {object} a - The analysis bundle.
 * @param {Array<object>} liens
 */
function renderExecutiveSummary(doc, a, liens) {
  sectionHeading(doc, '1. Executive Summary');
  para(doc,
    'Key figures for this case at a glance. The Visual Summary (section 2) charts ' +
    'these figures; the full underlying tables follow in the Annexure at the back.',
    { gap: 0.8 });

  const summary = a.summary || {};
  const cashout = a.cashout_analysis || {};
  const mules = a.mule_detection || [];
  const highMules = mules.filter((m) => m.risk_label === 'HIGH').length;
  // Two distinct figures — never conflate (see analyzer summary):
  //   • recoverableResidual: victim loss not yet cashed out / frozen / refunded.
  //   • lienTableTotal: Σ per-account lien-eligible balances (can exceed the loss).
  const recoverableResidual = num(summary.recoverable_residual);
  const lienTableTotal = num(summary.lien_table_total) || (liens || []).reduce(
    (s, l) => s + num(l.lien_amount ?? l.lien_eligible_amount), 0);
  const banks = new Set((liens || []).map((l) => l.bank_name).filter(Boolean)).size;
  const cashedOut = cashedOutForDisplay(summary, cashout);

  drawTable(doc, {
    fontSize: 10,
    columns: [
      { label: 'Metric', width: 300 },
      { label: 'Value', width: contentWidth(doc) - 300, align: 'right' },
    ],
    rows: [
      ['Total transactions analysed', formatCount(summary.total_transactions)],
      ['Victim loss (Layer 1)', formatMoney(summary.victim_loss_amount ?? summary.total_disputed_amount)],
      ['Total trail disputed (all layers)', formatMoney(summary.total_trail_disputed ?? summary.total_disputed_amount)],
      ['Layers in the money trail', formatCount(summary.total_layers)],
      ['Distinct beneficiary accounts', formatCount(summary.total_accounts)],
      ['Fraud trail start date', formatDate(summary.fraud_start_date)],
      ['Total confirmed cashed out (ATM/POS)', formatMoney(cashedOut)],
      ['Recoverable residual (loss - cashed out - on hold - refunded)', formatMoney(recoverableResidual)],
      ['Same-day ATM cashouts', formatCount(cashout.same_day_cashouts)],
      ['High-risk mule accounts', formatCount(highMules)],
      ['Accounts with lien-eligible balance', formatCount((liens || []).length)],
      ['Total lien-eligible balance across flagged accounts', formatMoney(lienTableTotal)],
      ['Banks to be contacted for lien', formatCount(banks)],
    ],
  });

  para(doc,
    'Recoverable residual is the share of the victim loss not yet cashed out, frozen, or refunded — ' +
    'it sums with those to 100% of the loss. The total lien-eligible balance is the per-account freezable ' +
    'sum and may exceed the victim loss because funds are re-counted as they traverse multiple layers.',
    { gap: 0.6, size: 8.5, color: MUTED });

  para(doc, 'Note: the Visual Summary (section 2) presents the money-flow network, ' +
    'layer breakdown, and daily-volume timeline as charts. Every supporting table ' +
    'is reproduced in full in the Annexure (A-H) at the back of this dossier.',
    { gap: 0, size: 8.5, color: MUTED });
}

/**
 * Place one rasterised chart (PNG buffer + authored px dimensions) at the
 * current cursor, scaled to the content width, with an italic caption beneath.
 * Adds a page first if the image + caption would overflow the current one.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{ png: Buffer, w: number, h: number }|null} chart
 * @param {string} caption
 */
function placeChart(doc, chart, caption) {
  const left = doc.page.margins.left;
  const w = contentWidth(doc);
  if (!chart || !chart.png) {
    para(doc, `[${caption}] — chart unavailable; see the Annexure tables for the data.`,
      { color: MUTED, gap: 0.8 });
    return;
  }
  const dispH = w * (chart.h / chart.w);
  // Reserve room for the image plus its caption line (~26pt).
  if (doc.y + dispH + 26 > doc.page.height - doc.page.margins.bottom) doc.addPage();
  doc.image(chart.png, left, doc.y, { width: w });
  doc.y += dispH + 3; // doc.image does not advance the cursor
  doc.font('Helvetica-Oblique').fontSize(8.5).fillColor(MUTED)
    .text(caption, left, doc.y, { width: w, align: 'left' });
  doc.x = left;
  doc.moveDown(1);
}

/**
 * Visual Summary — the charts section that sits up front (after the executive
 * summary). Renders the money-flow network, layer breakdown, and daily-volume
 * timeline as embedded PNGs; the same figures appear as full tables in the
 * Annexure. Degrades gracefully to a pointer note if rasterisation is
 * unavailable in this build.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{ available: boolean, network: object, layers: object, timeline: object }} charts
 */
function renderVisualSummary(doc, charts) {
  sectionHeading(doc, '2. Visual Summary');
  para(doc,
    'The fund trail at a glance. These charts are generated deterministically from ' +
    'the case data (same case -> same charts); the complete figures behind each are ' +
    'tabulated in the Annexure.', { gap: 0.8 });

  if (!charts || !charts.available) {
    para(doc,
      'Charts could not be rendered in this build of FinTrace. The complete ' +
      'underlying data is available as tables in the Annexure (A-H).', { color: MUTED });
    return;
  }

  placeChart(doc, charts.network,
    'Money-flow network: the heaviest account-to-account transfers, laid out by layer from the '
    + 'victim (left) to cash-out exit nodes (right). Edge width is proportional to the amount '
    + 'transferred; node colour marks the role (victim / mule / exit). Accounts are masked.');
  placeChart(doc, charts.layers,
    'Layer breakdown: total amount moved at each layer (hop) of the trail, showing how the '
    + 'funds fan out and thin as they move away from the victim.');
  placeChart(doc, charts.timeline,
    'Daily volume timeline: transaction volume per IST day across the trail. The green portion '
    + 'and markers flag days with same-day cash-outs, surfacing rapid-extraction clusters.');
}

/**
 * Annexure divider — a labelled separator page introducing the supporting data
 * tables that follow (moved to the back as part of the dossier reorganisation).
 *
 * @param {PDFKit.PDFDocument} doc
 */
function renderAnnexureDivider(doc) {
  const left = doc.page.margins.left;
  const w = contentWidth(doc);
  doc.moveDown(7);
  doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(28)
    .text('ANNEXURE', left, doc.y, { width: w, align: 'center' });
  doc.moveDown(0.4);
  doc.fillColor(MUTED).font('Helvetica').fontSize(14)
    .text('Supporting Data Tables', left, doc.y, { width: w, align: 'center' });
  doc.moveDown(1.5);
  doc.fillColor(INK).font('Helvetica').fontSize(10.5).text(
    'The annexures below (A-H) hold the complete underlying data summarised in the ' +
    'Executive Summary and charted in the Visual Summary: the per-layer aggregates, ' +
    'the money-flow edges, the mule-score ranking, the lien worksheet, the cash-out ' +
    'and geographic breakdowns, the daily timeline, and the bank-attribution review. ' +
    'The draft Section 102 Cr.P.C. lien-request letters follow the annexures.',
    left, doc.y, { width: w, align: 'center' });
  doc.x = left;
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} roadmap */
function renderRoadmap(doc, roadmap) {
  sectionHeading(doc, '3. Investigation Roadmap');
  para(doc,
    'Prioritised actions for the investigating officer, ordered P0 (act now) ' +
    'through P3 (corroborating evidence). Row colour signals urgency: ' +
    'P0 red, P1 amber, P2 blue, P3 grey.', { gap: 0.8 });

  const list = Array.isArray(roadmap) ? roadmap : [];
  if (list.length === 0) {
    para(doc, 'No roadmap actions were generated for this case.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 9,
    rowColors: list.map((r) => PRIORITY_COLOR[r.priority] || INK),
    columns: [
      { label: 'Priority', width: 75, align: 'center' },
      { label: 'Action', width: 165 },
      { label: 'Description', width: contentWidth(doc) - 240 },
    ],
    rows: list.map((r) => [
      PRIORITY_LABEL[r.priority] || r.priority || '—',
      asciiSafe(r.title),
      asciiSafe(r.description),
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} layers @param {object} [reconciliation] */
function renderLayers(doc, layers, reconciliation) {
  sectionHeading(doc, 'Annexure A — Layer-by-Layer Analysis');
  para(doc,
    'Each layer is one hop further from the victim. Funds typically fan out and ' +
    'speed up as they move outward toward cashout points.', { gap: 0.8 });

  if (!layers || layers.length === 0) {
    para(doc, 'No layer data available.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    columns: [
      { label: 'Layer', width: 55, align: 'center' },
      { label: 'Accounts', width: 70, align: 'right' },
      { label: 'Total Amount', width: 110, align: 'right' },
      { label: 'Disputed', width: 105, align: 'right' },
      { label: 'Cashouts', width: 70, align: 'right' },
      { label: 'Avg Fwd (hrs)', width: contentWidth(doc) - 410, align: 'right' },
    ],
    rows: layers.map((l) => [
      `L${l.layer_no}`,
      formatCount(l.account_count),
      formatMoney(l.total_amount),
      formatMoney(l.disputed_amount),
      formatCount(l.cashout_count),
      l.avg_forward_time_hours == null ? '—' : num(l.avg_forward_time_hours).toFixed(2),
    ]),
  });

  // Foot the per-layer Disputed column (HOP legs only) up to the headline Total
  // Trail Disputed. Cash-out (EXIT) and other (OTHER) legs also carry disputed
  // value but are not hops, so they are surfaced here rather than silently dropped.
  const rec = reconciliation && reconciliation.disputed;
  if (rec) {
    doc.moveDown(0.8);
    para(doc, 'Reconciliation to headline Total Trail Disputed', { bold: true, gap: 0.3 });
    // Feature 3 — the block foots LITERALLY to the headline:
    //   raw hop − duplicate hop legs collapsed + EXIT + OTHER (+ HOLD) = headline.
    // When exact-duplicate hop legs exist the collapse is an explicit, labelled
    // line (never a silent rounding); when none do (e.g. gold case 080512, whose
    // ₹409.56 leg is unique) the adjustment is 0 and the hop total is stated
    // directly. raw_hop/dedup are absent on pre-Feature-3 analyses; fall back to
    // net-hop only so older persisted analyses still render.
    const rawHop = rec.raw_hop != null ? num(rec.raw_hop) : num(rec.hop);
    const dedupAdj = num(rec.dedup_hop_adjustment);
    const reconRows = [];
    if (dedupAdj > 0.005) {
      reconRows.push(['Raw hop disputed (Money Transfer legs, incl. duplicates)', formatMoney(rawHop)]);
      reconRows.push(['Less: duplicate hop legs collapsed before analysis', formatMoney(-dedupAdj)]);
      reconRows.push(['Net hop disputed (= sum of per-layer Disputed above)', formatMoney(rec.hop)]);
    } else {
      reconRows.push(['Hop legs (sum of per-layer Disputed above)', formatMoney(rec.hop)]);
    }
    reconRows.push(['Add: Cash-out legs (EXIT) — dispositions, not hops', formatMoney(rec.exit)]);
    reconRows.push(['Add: Other legs (OTHER) — dispositions, not hops', formatMoney(rec.other)]);
    if (num(rec.hold) > 0) reconRows.push(['Add: Frozen / HOLD legs', formatMoney(rec.hold)]);
    reconRows.push(['Total Trail Disputed (headline)', formatMoney(rec.total)]);
    drawTable(doc, {
      columns: [
        { label: 'Reconciliation item', width: contentWidth(doc) - 150 },
        { label: 'Disputed', width: 150, align: 'right' },
      ],
      rows: reconRows,
      rowColors: reconRows.map((_, i) => (i === reconRows.length - 1 ? NAVY : INK)),
    });
    para(doc,
      'Annexure A aggregates hop (account-to-account) legs by layer. The components ' +
      'above sum exactly to the headline Total Trail Disputed; the duplicate-leg ' +
      'adjustment is shown explicitly, so no disputed leg is omitted or double-counted.',
      { color: MUTED, size: 8.5, gap: 0 });
  }
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {object} network - money_flow_network.
 * @param {Array<object>} [aggregators] - analysis.aggregators (connectivity collectors).
 */
function renderMoneyFlow(doc, network, aggregators) {
  sectionHeading(doc, 'Annexure B — Money Flow Network');
  para(doc,
    'The heaviest account-to-account transfers in the trail (top 10 by amount), ' +
    'aggregated across every hop between each pair. Account numbers are masked.',
    { gap: 0.8 });

  const edges = (network && Array.isArray(network.top_edges))
    ? network.top_edges.slice(0, 10) : [];
  if (edges.length === 0) {
    para(doc, 'No account-to-account edges were derived for this case.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 8.5,
    columns: [
      { label: 'Source A/c (masked)', width: 100 },
      { label: 'Destination (masked)', width: 100 },
      { label: 'Amount', width: 95, align: 'right' },
      { label: 'Txns', width: 40, align: 'right' },
      { label: 'Layers', width: 45, align: 'center' },
      { label: 'Bank', width: contentWidth(doc) - 380 },
    ],
    rows: edges.map((e) => [
      maskAccount(e.source),
      maskAccount(e.destination),
      formatMoney(e.amount),
      formatCount(e.txn_count),
      e.layers == null || e.layers === '' ? '—' : String(e.layers),
      asciiSafe(e.banks) || '—',
    ]),
  });

  // Top Aggregator Accounts (Feature 2) — collectors with in-degree >= 2, the
  // classic mule-collector hubs, ranked by fan-in. Lives inside Annexure B.
  const aggs = Array.isArray(aggregators) ? aggregators.slice(0, 10) : [];
  if (aggs.length > 0) {
    doc.moveDown(0.6);
    para(doc, 'Top Aggregator Accounts (collectors — in-degree >= 2)', { bold: true, gap: 0.3 });
    para(doc,
      'Accounts that gather funds from many distinct senders before forwarding — ' +
      'hub nodes in the network. In-degree = distinct senders; out-degree = distinct ' +
      'receivers. Bank names are IFSC-resolved.', { color: MUTED, size: 8.5, gap: 0.5 });
    drawTable(doc, {
      fontSize: 8.5,
      columns: [
        { label: '#', width: 24, align: 'center' },
        { label: 'Account (masked)', width: 110 },
        { label: 'Bank', width: contentWidth(doc) - 419 },
        { label: 'In-deg', width: 50, align: 'right' },
        { label: 'Out-deg', width: 55, align: 'right' },
        { label: 'Total In', width: 90, align: 'right' },
        { label: 'Total Out', width: 90, align: 'right' },
      ],
      rows: aggs.map((a, i) => [
        i + 1, maskAccount(a.account_no), asciiSafe(a.bank) || '—',
        formatCount(a.in_degree), formatCount(a.out_degree),
        formatMoney(a.total_in), formatMoney(a.total_out),
      ]),
    });
  }
}

/**
 * Circular-flow section (Feature 1) — placed after Money Flow Network. Real
 * simple loops (length <= 6) where money returns to an account it already passed
 * through; a strong layering indicator. Not lettered, so it never shifts the
 * Annexure A–H sequence.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {Array<object>} cycles - analysis.circular_flows
 */
function renderCircularFlows(doc, cycles) {
  sectionHeading(doc, 'Circular Flows — Layering Loops');
  para(doc,
    'Money that returns to an account it already passed through (simple loops of up ' +
    'to six accounts). Legitimate funds do not circle back, so a cycle is a strong ' +
    'layering indicator. "Loop amount" is the thinnest leg of the loop — the most ' +
    'that could actually have circulated around it. Account numbers are masked; ' +
    'bank names are IFSC-resolved.', { gap: 0.8 });

  const list = Array.isArray(cycles) ? cycles.slice(0, 10) : [];
  if (list.length === 0) {
    para(doc, 'No circular flows were detected in this trail.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 8.5,
    columns: [
      { label: '#', width: 24, align: 'center' },
      { label: 'Cycle (masked account loop)', width: contentWidth(doc) - 320 },
      { label: 'Len', width: 38, align: 'center' },
      { label: 'Loop Amount', width: 95, align: 'right' },
      { label: 'Txns', width: 40, align: 'right' },
      { label: 'Banks', width: 123 },
    ],
    rows: list.map((c, i) => {
      const path = Array.isArray(c.path) ? c.path : [];
      const loop = path.map(maskAccount).join(' -> ') + (path.length ? ` -> ${maskAccount(path[0])}` : '');
      return [
        i + 1, loop, formatCount(c.length), formatMoney(c.amount),
        formatCount(c.txns), asciiSafe((c.banks || []).join(', ')) || '—',
      ];
    }),
  });

  para(doc,
    `${formatCount(list.length)} circular flow(s) detected — recommend priority review of the looping accounts.`,
    { bold: true, gap: 0, size: 9 });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} mules */
function renderMules(doc, mules) {
  sectionHeading(doc, 'Annexure C — Top Mule Accounts');
  para(doc,
    'Accounts ranked by mule risk score — an uncapped points total (a textbook ' +
    'mule trips every signal and can exceed 100); higher = stronger indicators. ' +
    'Ties break by larger inflow. HIGH-risk accounts are the priority targets ' +
    'for lien and KYC requests. Account numbers are masked for the report.',
    { gap: 0.8 });

  const top = (mules || []).slice(0, 10);
  if (top.length === 0) {
    para(doc, 'No mule accounts were scored.', { color: MUTED });
    return;
  }

  drawTable(doc, {
    fontSize: 8.5,
    rowColors: top.map((m) => RISK_COLOR[m.risk_label] || INK),
    columns: [
      { label: '#', width: 24, align: 'center' },
      { label: 'Account (masked)', width: 95 },
      { label: 'Bank', width: 95 },
      { label: 'Layer', width: 42, align: 'center' },
      { label: 'Score', width: 42, align: 'right' },
      { label: 'Risk', width: 55, align: 'center' },
      { label: 'Received', width: contentWidth(doc) - 353, align: 'right' },
    ],
    rows: top.map((m, i) => [
      i + 1,
      maskAccount(m.account_no),
      m.bank_name || '—',
      m.layer_no == null ? '—' : `L${m.layer_no}`,
      formatCount(m.mule_score),
      m.risk_label || '—',
      formatMoney(m.total_received),
    ]),
  });
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} liens */
function renderLien(doc, liens) {
  sectionHeading(doc, 'Annexure D — Lien-Eligible Amounts');
  para(doc,
    'Lien-eligible balance per account — disputed inflow not yet confirmed withdrawn ' +
    'as cash. Subject to the actual available balance confirmed by the bank.',
    { gap: 0.8 });

  if (!liens || liens.length === 0) {
    para(doc, 'No accounts currently carry a lien-eligible balance.', { color: MUTED });
    return;
  }

  const total = liens.reduce((s, l) => s + num(l.lien_amount ?? l.lien_eligible_amount), 0);
  drawTable(doc, {
    fontSize: 8.5,
    columns: [
      { label: '#', width: 24, align: 'center' },
      { label: 'Account (masked)', width: 100 },
      { label: 'Bank', width: 110 },
      { label: 'IFSC', width: 85 },
      { label: 'Status', width: 60, align: 'center' },
      { label: 'Lien Amount', width: contentWidth(doc) - 379, align: 'right' },
    ],
    rows: liens.map((l, i) => [
      i + 1,
      maskAccount(l.account_no),
      l.bank_name || '—',
      l.ifsc_code || '—',
      l.lien_status || 'pending',
      formatMoney(l.lien_amount ?? l.lien_eligible_amount),
    ]),
  });

  para(doc, `Total lien-eligible balance across ${formatCount(liens.length)} flagged account(s): ` +
    `${formatMoney(total)}.`, { bold: true, gap: 0.4 });
  para(doc,
    '(May exceed the victim loss as funds traverse multiple layers — this is the freezable ' +
    'per-account balance, not the recoverable residual reported in the Executive Summary.)',
    { gap: 0.6, size: 8, color: MUTED });

  // Feature 4 — the exact per-account formula + exclusion rule, printed here so a
  // reviewer can reconstruct the total. Full per-account audit columns (incl.
  // Disputed Forwarded and the cap reason) are in the Excel "Lien Calculation" sheet.
  para(doc, 'Per-account formula & exclusion rule', { bold: true, gap: 0.2, size: 9 });
  para(doc,
    'Gross Balance = max(0, Received - Forwarded - On Hold - Cashed Out). ' +
    'Lien = max(0, min(Gross Balance, Disputed Inflow)). ' +
    'EXCLUDED: any gross residue above an account\'s disputed (fraud-attributed) inflow — its ' +
    'own/clean funds; and money received via OTHER settlement legs, sub-Rs.500 legs, or ' +
    'wallet/PA/PG ids without a resolvable IFSC, which carry no disputed-hop inflow and so ' +
    'cannot raise the cap. Per-account audit columns are in the Excel Lien Calculation sheet.',
    { gap: 0, size: 8, color: MUTED });
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {object} cashout
 * @param {{ atmTerminals: Array<object>, recon: object }} view -
 *   Writer-side scoped views: ATM-only terminal aggregates (POS merchant
 *   terminals are listed under Geographic Hotspots instead) and the
 *   gross-vs-confirmed reconciliation.
 */
function renderCashout(doc, cashout, view) {
  sectionHeading(doc, 'Annexure E — Cashout Analysis');
  const c = cashout || {};
  const { atmTerminals = [], recon = null } = view || {};

  para(doc, `Total confirmed cashed out (ATM + POS): ${formatMoney(c.total_cashout_amount)} ` +
    `across ${formatCount(c.total_cashout_transactions)} transaction(s).`, { gap: 0.3 });
  para(doc, `Same-day ATM cashouts: ${formatCount(c.same_day_cashouts)}` +
    (c.fastest_cashout_hours != null
      ? `   |   Fastest cashout: ${num(c.fastest_cashout_hours).toFixed(2)} hours after victim debit.`
      : '.'), { gap: 0.9 });

  if (atmTerminals.length > 0) {
    para(doc, 'ATM withdrawal locations (gross amounts, highest value first):', { bold: true, gap: 0.5 });
    drawTable(doc, {
      fontSize: 8.5,
      // Give the amount a fixed, generous right-aligned column so rupee values
      // and the "Gross Amount" header never wrap mid-number; the narrow ID/City/
      // State/Hits columns are fixed too, and Location absorbs the remaining
      // width (long addresses wrap to multiple lines rather than squeezing the
      // numbers). Widths sum to exactly contentWidth.
      columns: [
        { label: 'ATM ID', width: 72 },
        { label: 'Location', width: contentWidth(doc) - 336, align: 'left' },
        { label: 'City', width: 68 },
        { label: 'State', width: 62 },
        { label: 'Gross Amount', width: 100, align: 'right' },
        { label: 'Hits', width: 34, align: 'right' },
      ],
      rows: atmTerminals.map((a) => [
        a.atm_id || '—',
        a.atm_location || '—',
        a.city || '—',
        a.state || '—',
        formatMoney(a.amount),
        formatCount(a.count),
      ]),
    });
  } else {
    para(doc, 'No ATM withdrawals were detected in this trail (POS merchant ' +
      'cash-outs, if any, are listed under Geographic Hotspots).', { color: MUTED, gap: 0.9 });
  }

  // Gross-vs-confirmed reconciliation: a reader who sums the ATM table above
  // and the POS merchant table (section 9) gets the gross figure; this line
  // shows exactly how that reconciles to the confirmed headline.
  if (recon && (recon.rows_shown > 0 || recon.confirmed > 0)) {
    // The detail tables show POST-dedup figures, so the gross shown is normally
    // already net of the collapsed duplicates (dup_amount_shown ≈ 0). In that
    // case we must NOT subtract a "Rs. 0.00 duplicate rows" term (it reads as a
    // contradiction with the non-zero collapsed-row count); we state instead
    // that the gross is already net of them. Only when the detail tables truly
    // carry duplicate value do we show the explicit "- duplicates" term.
    const hasDupValue = num(recon.dup_amount_shown) > 0.005;
    const dupNote = recon.dup_rows_collapsed > 0
      ? (hasDupValue
        ? `, net of ${formatMoney(recon.dup_amount_shown)} across ` +
          `${formatCount(recon.dup_rows_collapsed)} duplicate ledger row(s)`
        : ` (already net of ${formatCount(recon.dup_rows_collapsed)} exact-duplicate ` +
          `ledger row(s) collapsed before analysis)`)
      : '';
    const formula = hasDupValue ? 'gross - duplicates - cap = confirmed' : 'gross - cap = confirmed';
    para(doc,
      `Reconciliation: gross withdrawals shown (ATM table above + POS merchants in section 9): ` +
      `${formatMoney(recon.gross_shown)} across ${formatCount(recon.rows_shown)} row(s)${dupNote}. ` +
      `Confirmed cashed out: ${formatMoney(recon.confirmed)} — less ` +
      `${formatMoney(recon.cap_excess)} capped at disputed inflow per account ` +
      `(amounts above an account's disputed inflow are its own/clean funds): ` +
      `${formula}.`,
      { gap: 0.9, size: 8.5, color: MUTED });
  }

  const byState = c.cashout_by_state || [];
  if (byState.length > 0) {
    para(doc, 'Cashout distribution by state:', { bold: true, gap: 0.5 });
    drawTable(doc, {
      fontSize: 9,
      columns: [
        { label: 'State', width: 220 },
        { label: 'Cashout Amount', width: 150, align: 'right' },
        { label: 'Count', width: contentWidth(doc) - 370, align: 'right' },
      ],
      rows: byState.map((s) => [s.state, formatMoney(s.amount), formatCount(s.count)]),
    });
  }
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {object} geography
 * @param {Array<object>} posMerchants - Writer-side POS merchant aggregates
 *   derived from the raw ledger; used when the analyzer's top_merchants view
 *   is empty (POS legs carrying a terminal id are bucketed as ATM there).
 */
function renderGeography(doc, geography, posMerchants) {
  sectionHeading(doc, 'Annexure F — Geographic Hotspots');
  const g = geography || {};
  const byState = Array.isArray(g.by_state) ? g.by_state : [];
  const analyzerMerchants = Array.isArray(g.top_merchants) ? g.top_merchants : [];
  const merchants = analyzerMerchants.length
    ? analyzerMerchants : (Array.isArray(posMerchants) ? posMerchants : []);

  para(doc, 'Where the cashed-out funds surfaced — by state, and by merchant ' +
    '(POS terminals). Useful for jurisdiction and on-ground follow-up.', { gap: 0.8 });

  para(doc, 'Cashout by state:', { bold: true, gap: 0.5 });
  if (byState.length > 0) {
    drawTable(doc, {
      fontSize: 9,
      columns: [
        { label: 'State', width: 200 },
        { label: 'Amount', width: 130, align: 'right' },
        { label: 'Txns', width: 70, align: 'right' },
        { label: 'Share %', width: contentWidth(doc) - 400, align: 'right' },
      ],
      rows: byState.map((s) => [
        asciiSafe(s.state) || '—',
        formatMoney(s.amount),
        formatCount(s.txn_count ?? s.count),
        `${num(s.pct).toFixed(1)}%`,
      ]),
    });
  } else {
    para(doc, 'No state-level location data was present in this NCRP export.',
      { color: MUTED, gap: 0.9 });
  }

  para(doc, 'Top merchants (POS cashouts, gross amounts):', { bold: true, gap: 0.5 });
  if (merchants.length > 0) {
    drawTable(doc, {
      fontSize: 9,
      columns: [
        { label: 'Merchant Name', width: 200 },
        { label: 'Terminal ID', width: 90 },
        { label: 'Type', width: 70 },
        { label: 'Gross Amount', width: 110, align: 'right' },
        { label: 'Txns', width: contentWidth(doc) - 470, align: 'right' },
      ],
      rows: merchants.slice(0, 10).map((m) => [
        asciiSafe(m.name) || '—',
        asciiSafe(m.terminal_id) || '—',
        asciiSafe(m.type) || 'Merchant',
        formatMoney(m.amount),
        formatCount(m.txn_count),
      ]),
    });
  } else {
    para(doc, 'No POS / merchant cashouts were detected in this trail.',
      { color: MUTED, gap: 0 });
  }
}

/** @param {PDFKit.PDFDocument} doc @param {Array<object>} timeline @param {object} [reconciliation] */
function renderTimeline(doc, timeline, reconciliation, dayOfWeek) {
  sectionHeading(doc, 'Annexure G — Timeline Summary');
  para(doc, 'Daily money movement across the fraud trail (IST calendar days).',
    { gap: 0.8 });

  if (!timeline || timeline.length === 0) {
    para(doc, 'No dated transactions available for a timeline.', { color: MUTED });
    return;
  }

  // Daily rows are dated transactions only; undated rows have no calendar day so
  // they cannot sit on the timeline — list them as a single "Undated" row so the
  // visible count foots to the unique-transaction total.
  const tx = reconciliation && reconciliation.transactions;
  const rows = timeline.map((t) => [
    formatDate(t.date),
    formatCount(t.transaction_count),
    formatMoney(t.total_amount),
  ]);
  if (tx && tx.undated > 0) {
    rows.push(['Undated', formatCount(tx.undated), formatMoney(tx.undated_amount)]);
  }

  drawTable(doc, {
    columns: [
      { label: 'Date', width: 160 },
      { label: 'Transactions', width: 130, align: 'right' },
      { label: 'Total Amount', width: contentWidth(doc) - 290, align: 'right' },
    ],
    rows,
  });

  if (tx) {
    const uniqueTotal = num(tx.dated) + num(tx.undated);
    para(doc,
      `Rows above sum to ${formatCount(uniqueTotal)} unique transactions ` +
      `(${formatCount(tx.dated)} dated + ${formatCount(tx.undated)} undated). ` +
      `A further ${formatCount(tx.duplicates)} exact-duplicate ledger row(s) were ` +
      `removed before analysis; counting those, the raw ledger holds ` +
      `${formatCount(tx.raw_legs)} legs — the headline Total Transactions.`,
      { color: MUTED, size: 8.5, gap: 0 });
  }

  // Feature 5 — small day-of-week table (IST weekday of each leg).
  if (dayOfWeek && Array.isArray(dayOfWeek.weekdays) && dayOfWeek.weekdays.length) {
    doc.moveDown(0.8);
    para(doc, 'Activity by day of week (IST)', { bold: true, gap: 0.4 });
    const dRows = dayOfWeek.weekdays.map((w) => [
      w.weekday, formatCount(w.txns), formatMoney(w.totalAmount),
    ]);
    if (dayOfWeek.undated && dayOfWeek.undated.txns > 0) {
      dRows.push(['Undated', formatCount(dayOfWeek.undated.txns), formatMoney(dayOfWeek.undated.totalAmount)]);
    }
    drawTable(doc, {
      columns: [
        { label: 'Weekday', width: 160 },
        { label: 'Transactions', width: 130, align: 'right' },
        { label: 'Total Amount', width: contentWidth(doc) - 290, align: 'right' },
      ],
      rows: dRows,
    });
  }
}

/** @param {PDFKit.PDFDocument} doc @param {string[]} findings */
function renderFindings(doc, findings) {
  sectionHeading(doc, '4. Key Findings & Recommended Actions');

  const list = Array.isArray(findings) ? findings : [];
  if (list.length === 0) {
    para(doc, 'No automated findings were generated for this case.', { color: MUTED });
    return;
  }

  const left = doc.page.margins.left;
  list.forEach((f, i) => {
    if (doc.y + 40 > doc.page.height - doc.page.margins.bottom) doc.addPage();
    doc.font('Helvetica-Bold').fontSize(11).fillColor(NAVY_LIGHT)
      .text(`${i + 1}.`, left, doc.y, { width: 22, continued: false });
    doc.moveUp();
    doc.font('Helvetica').fontSize(10.5).fillColor(INK)
      .text(String(f), left + 22, doc.y, { width: contentWidth(doc) - 22 });
    doc.moveDown(0.6);
    doc.x = left;
  });
}

/**
 * Short, human label for a bank-attribution flag (used in the table column).
 * @param {string} flag
 */
function flagLabel(flag) {
  switch (flag) {
    case 'IFSC_TEXT_MISMATCH': return 'IFSC vs text';
    case 'NO_IFSC': return 'No IFSC';
    case 'INVALID_IFSC': return 'Invalid IFSC';
    case 'UNKNOWN_IFSC_PREFIX': return 'Unknown prefix';
    default: return flag || '—';
  }
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {Array<object>} dataQuality
 * @param {Array<object>} [oldTransactions] - rows >6 months old, excluded from figures
 * @param {Array<object>} [parseWarnings] - self-healing parse audit (fuzzy matches / degraded columns)
 */
function renderDataQuality(doc, dataQuality, oldTransactions = [], parseWarnings = []) {
  const list = Array.isArray(dataQuality) ? dataQuality : [];
  const oldTxns = Array.isArray(oldTransactions) ? oldTransactions : [];
  const pw = Array.isArray(parseWarnings) ? parseWarnings : [];
  doc.addPage();
  sectionHeading(doc, 'Annexure H — Bank Attribution — Data Quality Review');

  if (list.length === 0) {
    para(doc,
      'Every account resolved cleanly: the bank name on each lien letter was ' +
      'derived from a valid IFSC that agreed with the source file. No accounts ' +
      'require manual bank verification.', { color: MUTED });
  } else {
    para(doc,
      `${formatCount(list.length)} account(s) below need the investigating officer to ` +
      'confirm the freeze target. The bank printed on each lien letter is taken from ' +
      "the account's IFSC (authoritative); where the source file's text disagreed or " +
      'no usable IFSC was present, it is listed here for review. The financial amounts ' +
      'are unaffected — only the bank attribution is flagged.', { gap: 0.8 });

    drawTable(doc, {
      fontSize: 8,
      columns: [
        { label: '#', width: 22, align: 'center' },
        { label: 'Account (masked)', width: 96 },
        { label: 'Resolved bank (letter)', width: 120 },
        { label: 'IFSC', width: 76 },
        { label: 'Flag', width: 64 },
        { label: 'Source-file text', width: contentWidth(doc) - 378 },
      ],
      rows: list.map((d, i) => [
        i + 1,
        maskAccount(d.account_no),
        d.bank || '—',
        d.ifsc_code || '—',
        flagLabel(d.bank_flag),
        d.raw_bank || '(blank)',
      ]),
    });

    para(doc,
      'Action: for "IFSC vs text" rows the letter already uses the IFSC-derived bank — ' +
      'verify and dispatch. For "No IFSC" / "Invalid IFSC" rows (wallets / PA / PG ids) ' +
      'confirm the correct nodal entity. For "Unknown prefix" rows the IFSC bank map ' +
      'should be extended.', { gap: 0.8, size: 8, color: MUTED });
  }

  // Parser self-healing audit: sheets/columns resolved by similarity rather
  // than an exact match, plus informational columns that were absent. Recorded
  // so the file's interpretation is fully auditable. Amounts are unaffected.
  if (pw.length > 0) {
    const typeLabel = (code) => (
      code === 'FUZZY_SHEET_MATCH' ? 'Sheet (fuzzy)'
        : code === 'FUZZY_COLUMN_MATCH' ? 'Column (fuzzy)'
          : 'Column missing');
    para(doc,
      `Parser Self-Healing Audit — ${formatCount(pw.length)} item(s). The parser could not ` +
      'match the following sheet/column name(s) exactly; entries marked "fuzzy" were resolved ' +
      'by name similarity (confidence shown) and entries marked "missing" degraded gracefully. ' +
      'This records how the source file was READ — it does not change any computed amount. ' +
      'Confirm each interpretation is correct.', { gap: 0.8, size: 8 });

    drawTable(doc, {
      fontSize: 8,
      columns: [
        { label: '#', width: 22, align: 'center' },
        { label: 'Type', width: 86 },
        { label: 'Sheet', width: 90 },
        { label: 'Source name → field', width: 150 },
        { label: 'Conf.', width: 38, align: 'center' },
        { label: 'Note', width: contentWidth(doc) - 386 },
      ],
      rows: pw.map((w, i) => [
        i + 1,
        typeLabel(w.code),
        w.sheet || '—',
        `${w.matchedFrom || '(missing)'} → ${w.matchedTo || '—'}`,
        w.confidence == null ? '—' : `${Math.round(w.confidence * 100)}%`,
        w.message || '',
      ]),
    });
  }

  // Old transactions (>6 months): parsed and recorded, but excluded from every
  // financial figure — listed so the file is fully accounted for.
  if (oldTxns.length > 0) {
    para(doc,
      `Old Transactions (excluded from calculations) — ${formatCount(oldTxns.length)} ` +
      'transaction(s) in the source file predate the 6-month NCRP window. They are ' +
      'informational only and contribute to no victim-loss, cash-out, lien, or mule ' +
      'figure in this dossier.', { gap: 0.8 });

    drawTable(doc, {
      fontSize: 8,
      columns: [
        { label: '#', width: 22, align: 'center' },
        { label: 'Account (masked)', width: 110 },
        { label: 'Bank', width: 150 },
        { label: 'Layer', width: 44, align: 'center' },
        { label: 'Amount', width: 80, align: 'right' },
        { label: 'Remarks', width: contentWidth(doc) - 406 },
      ],
      rows: oldTxns.map((o, i) => [
        i + 1,
        maskAccount(o.account_no),
        o.bank || '—',
        o.layer_no == null ? '—' : o.layer_no,
        formatMoney(o.transaction_amount),
        o.remarks || '—',
      ]),
    });
  }
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {Array<object>} emails - actionable per-bank §102 letters
 * @param {object} [analysis] - parsed analysis_json; supplies the lien worksheet
 *   (for the wallet/masked sections) and the freeze-target set (for the per-
 *   letter reviewer note). Falls back gracefully when absent.
 */
function renderEmails(doc, emails, analysis) {
  const list = Array.isArray(emails) ? emails : [];
  const aj = analysis && typeof analysis === 'object' ? analysis : {};
  // The "verify bank" set — lien accounts whose bank could not be confirmed from
  // a valid IFSC (same set the on-screen page caveat and the Lien ⚠ flag use).
  const freezeSet = new Set(
    (aj.data_quality_summary && aj.data_quality_summary.freeze_target_accounts) || []
  );
  // Non-actionable instruments pulled out of the letters, derived from the same
  // lien worksheet so the dossier still shows them (evidence is never dropped).
  const { wallet_instruments = [], masked_accounts = [] } =
    buildEmailArtifacts(0, Array.isArray(aj.lien_calculation) ? aj.lien_calculation : [], {});

  doc.addPage();
  sectionHeading(doc, 'Draft Lien-Request Emails (Section 102 Cr.P.C.)');

  if (list.length === 0 && wallet_instruments.length === 0 && masked_accounts.length === 0) {
    para(doc, 'No draft emails were generated (no lien-eligible accounts).',
      { color: MUTED });
    return;
  }

  const left = doc.page.margins.left;

  if (list.length > 0) {
    para(doc,
      `${formatCount(list.length)} per-bank letter(s) below — copy the subject and ` +
      'body into your email client. Each cites Section 102 Cr.P.C. read with the IT ' +
      'Act, 2000. Wallet / PA / VPA instruments and masked accounts are listed ' +
      'separately after the letters (they cannot be served a bank freeze notice).',
      { gap: 0.8 });

    list.forEach((email, idx) => {
      if (idx > 0) doc.addPage();
      else if (doc.y + 120 > doc.page.height - doc.page.margins.bottom) doc.addPage();

      doc.font('Helvetica-Bold').fontSize(12).fillColor(NAVY)
        .text(`Letter ${idx + 1} of ${list.length} — ${email.bank_name || 'Unknown Bank'}`,
          left, doc.y, { width: contentWidth(doc) });
      doc.moveDown(0.4);
      doc.x = left;

      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(INK)
        .text('Subject: ', left, doc.y, { continued: true })
        .font('Helvetica').text(email.subject || '', { width: contentWidth(doc) });
      doc.moveDown(0.6);
      doc.x = left;

      // Body in a monospace font so the account table lines up; the issue date
      // is injected here (the stored body is date-free) so the dossier letter
      // bears the date it was produced. PDFKit flows it across pages.
      doc.font('Courier').fontSize(8.5).fillColor(INK)
        .text(composeLetterText(email.body || ''), left, doc.y,
          { width: contentWidth(doc), align: 'left' });
      doc.x = left;

      // Reviewer note (NOT part of the dispatched letter): any account in this
      // letter whose bank could not be confirmed from a valid IFSC — verify
      // before sending.
      const flagged = (Array.isArray(email.account_list) ? email.account_list : [])
        .filter((acc) => freezeSet.has(String(acc)));
      if (flagged.length) {
        doc.moveDown(0.6);
        doc.x = left;
        doc.font('Helvetica-Oblique').fontSize(7.5).fillColor(MUTED)
          .text(
            'Reviewer note (not part of the dispatched letter): bank attribution could ' +
            `not be confirmed from a valid IFSC for account(s): ${flagged.map(maskAccount).join(', ')}. ` +
            'Verify the freeze target before dispatch. See Annexure H (Data Quality).',
            left, doc.y, { width: contentWidth(doc) });
        doc.x = left;
      }
    });
  }

  // ── Non-actionable section 1: wallet / PA / PG / UPI-VPA instruments ──────
  if (wallet_instruments.length > 0) {
    doc.addPage();
    sectionHeading(doc, 'Verify Nodal Entity — Wallet / PA / VPA Instruments');
    para(doc,
      `${formatCount(wallet_instruments.length)} instrument(s) below are payment ` +
      'wallets / aggregators / gateways or UPI VPAs, NOT bank accounts — a wallet/PA ' +
      'cannot place a Section 102 lien. Identify the nodal/escrow bank holding these ' +
      'funds before issuing a request; the "Source Ref" is the raw value from the ' +
      'source IFSC cell and is NOT a bank IFSC. Listed here (with amount) so no ' +
      'instrument is dropped from the trail.', { gap: 0.8 });
    const wTotal = wallet_instruments.reduce((s, w) => s + num(w.amount), 0);
    drawTable(doc, {
      fontSize: 8.5,
      columns: [
        { label: '#', width: 24, align: 'center' },
        { label: 'Instrument', width: 150 },
        { label: 'Entity (as named in source)', width: 150 },
        { label: 'Source Ref (not an IFSC)', width: 90 },
        { label: 'Amount', width: contentWidth(doc) - 414, align: 'right' },
      ],
      rows: wallet_instruments.map((w, i) => [
        i + 1, w.account_no || '—', w.bank_name || 'Unknown', w.source_ref || '—',
        formatMoney(w.amount),
      ]),
    });
    para(doc, `Total across ${formatCount(wallet_instruments.length)} wallet/PA/VPA ` +
      `instrument(s): ${formatMoney(wTotal)} (excluded from the bank letters above; ` +
      'verify the nodal entity).', { bold: true, gap: 0.4 });
  }

  // ── Non-actionable section 2: masked / unresolvable account numbers ───────
  if (masked_accounts.length > 0) {
    doc.addPage();
    sectionHeading(doc, 'Unresolvable / Masked Accounts — Non-Actionable');
    para(doc,
      `${formatCount(masked_accounts.length)} account(s) below carry a masked or ` +
      'unresolvable account number in the source (e.g. "XXXX", "NA") — a bank cannot ' +
      'action a freeze on an unidentifiable account. Obtain the full account number ' +
      'before issuing the request. Listed here (with amount) so nothing is dropped.',
      { gap: 0.8 });
    const mTotal = masked_accounts.reduce((s, m) => s + num(m.amount), 0);
    drawTable(doc, {
      fontSize: 8.5,
      columns: [
        { label: '#', width: 24, align: 'center' },
        { label: 'Account (as in source)', width: 150 },
        { label: 'Bank', width: 160 },
        { label: 'IFSC', width: 85 },
        { label: 'Amount', width: contentWidth(doc) - 419, align: 'right' },
      ],
      rows: masked_accounts.map((m, i) => [
        i + 1, m.account_no || '—', m.bank_name || 'Unknown', m.ifsc_code || '—',
        formatMoney(m.amount),
      ]),
    });
    para(doc, `Total across ${formatCount(masked_accounts.length)} masked account(s): ` +
      `${formatMoney(mTotal)} (excluded from the bank letters above; obtain the full ` +
      'account number).', { bold: true, gap: 0.4 });
  }
}

// ─── Footer pass ─────────────────────────────────────────────────────

/**
 * Stamp every buffered page with the brand footer and "Page x of N".
 *
 * The footer sits below the content area, inside the bottom-margin band. Text
 * positioned there would normally make PDFKit auto-add a page (it thinks the
 * line doesn't fit), so the bottom margin is zeroed for the duration of each
 * write and then restored — the standard recipe for fixed footers.
 *
 * The source SHA-256 (when known) is stamped on a thin sub-line beneath the
 * brand footer of EVERY page, so a single extracted page still carries the hash
 * that ties it back to the source file.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {{ sha256: string|null, version: string }} [provenance]
 */
function stampFooters(doc, provenance = {}) {
  const range = doc.bufferedPageRange();
  const provLine = provenance && provenance.sha256
    ? `Source SHA-256: ${provenance.sha256}  |  FinTrace v${provenance.version || appVersion()}`
    : null;
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);

    const restoreBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0; // suppress auto page-break in the footer band

    const left = doc.page.margins.left;
    const width = contentWidth(doc);
    const y = doc.page.height - 32;

    doc.moveTo(left, y - 6).lineTo(left + width, y - 6)
      .lineWidth(0.5).strokeColor(BORDER).stroke();
    doc.font('Helvetica').fontSize(8).fillColor(MUTED);
    doc.text(BRAND_FOOTER, left, y, { width, align: 'left', lineBreak: false });
    doc.text(`Page ${i + 1} of ${range.count}`, left, y, { width, align: 'right', lineBreak: false });

    // Provenance sub-line (centred, just below the brand line).
    if (provLine) {
      doc.font('Courier').fontSize(6.5).fillColor(MUTED);
      doc.text(provLine, left, y + 11, { width, align: 'center', lineBreak: false });
    }

    doc.page.margins.bottom = restoreBottom;
  }
}

// ─── Public API ──────────────────────────────────────────────────────

/**
 * Generate the investigation PDF for one report and write it to `outputPath`.
 *
 * The promise resolves with `outputPath` once the file stream has fully
 * flushed, or rejects if PDFKit or the write stream errors. The parent
 * directory is created if missing.
 *
 * @param {{
 *   report?: Record<string, unknown>,
 *   analysis?: Record<string, unknown>,
 *   liens?: Array<Record<string, unknown>>,
 *   emails?: Array<Record<string, unknown>>,
 *   layers?: Array<Record<string, unknown>>,
 *   transactions?: Array<Record<string, unknown>>,
 *   ack_no?: string|null,
 *   complaint_date?: string|null,
 * }} data - The report's analysis bundle (analysis = parsed analysis_json).
 *   `transactions` (the raw ledger) drives the writer-side ATM/POS split and
 *   the POS merchant table; without it those sections fall back to the
 *   analyzer's views.
 * @param {string} outputPath - Absolute path of the .pdf to write.
 * @returns {Promise<string>} Resolves to `outputPath`.
 *
 * @example
 *   await generateReportPdf({ report, analysis, liens, emails, layers },
 *     path.join(exportsDir, 'FinTrace-NCRP123-1716800000000.pdf'));
 */
function generateReportPdf(data, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    } catch (err) {
      reject(new Error(`generateReportPdf: cannot create output directory: ${err.message}`));
      return;
    }

    const {
      report = {}, analysis = {}, liens = [], emails = [], layers = [], transactions = [],
    } = data || {};
    const summary = analysis.summary || {};
    // Prefer persisted layer rows; fall back to the analysis snapshot.
    const layerRows = (layers && layers.length) ? layers : (analysis.layer_analysis || []);
    const ackNo = (data && data.ack_no) || report.ack_no || `report-${report.id ?? '—'}`;

    // Writer-side ATM/POS scoping + gross-vs-confirmed reconciliation (shared
    // with the XLSX export via exportViews — presentation only, no money math).
    // With no ledger available the ATM table falls back to the analyzer's full
    // terminal list, exactly as before.
    const cashoutView = analysis.cashout_analysis || {};
    const atmTerminals = transactions.length
      ? atmOnlyCashouts(cashoutView.atm_cashouts || [], transactions)
      : (cashoutView.atm_cashouts || []);
    const geoView = analysis.geography || {};
    // Ledger-derived merchants are complete (the analyzer's top_merchants view
    // is name-grouped, top-10, and empty whenever POS legs carry terminal ids).
    const posMerchants = transactions.length
      ? posMerchantAggregates(transactions)
      : (Array.isArray(geoView.top_merchants) ? geoView.top_merchants : []);
    const atmShownAmount = atmTerminals.reduce((s, a) => s + num(a.amount), 0);
    const atmShownTxns = atmTerminals.reduce((s, a) => s + num(a.count), 0);
    const posShownAmount = posMerchants.reduce((s, m) => s + num(m.amount), 0);
    const posShownTxns = posMerchants.reduce((s, m) => s + num(m.txn_count), 0);
    const cashoutRecon = cashoutReconciliation(
      { summary, cashout: cashoutView },
      atmShownAmount + posShownAmount, atmShownTxns + posShownTxns);

    // Visual-summary charts: SVG built + rasterised to deterministic PNGs (same
    // case -> same charts). Wrapped so a rasteriser failure can never abort the
    // dossier — renderCharts degrades to nulls and the Visual Summary prints a
    // pointer to the Annexure tables instead.
    let charts;
    try {
      charts = renderCharts(analysis, transactions);
    } catch (err) {
      charts = { available: false, network: null, layers: null, timeline: null };
    }

    // Evidentiary provenance, read from the persisted report record (with
    // explicit-override fallbacks so callers/tests can pass it directly).
    const provenance = {
      sha256: report.source_sha256 ?? (data && data.source_sha256) ?? null,
      filename: report.original_filename ?? (data && data.source_filename) ?? null,
      ingestedAt: report.upload_date ?? (data && data.upload_date) ?? null,
      // A persisted app_version of "unknown" (older uploads, before the version
      // was wired in) must not mask the real version — treat it as absent so
      // appVersion() fills in.
      version: (data && typeof data.app_version === 'string' && data.app_version.trim()
        && data.app_version.trim().toLowerCase() !== 'unknown')
        ? data.app_version.trim() : appVersion(),
    };

    const doc = new PDFDocument({
      size: 'A4',
      margin: PAGE_MARGIN,
      bufferPages: true,
      info: {
        Title: `FinTrace NCRP Investigation Report — ${ackNo}`,
        Author: 'FinTrace NCRP | MINT',
        Subject: 'Cyber Crime Financial Trail Analysis',
        // Embed the source hash in the PDF metadata (item 3) so the provenance
        // survives even if the document text is stripped.
        Keywords: provenance.sha256
          ? `source-sha256:${provenance.sha256}; source-file:${provenance.filename || ''}; `
            + `fintrace-version:${provenance.version}`
          : `fintrace-version:${provenance.version}`,
        Creator: `FinTrace NCRP v${provenance.version}`,
      },
    });

    const stream = fs.createWriteStream(outputPath);
    let settled = false;
    const fail = (err) => {
      if (settled) return;
      settled = true;
      reject(err instanceof Error ? err : new Error(String(err)));
    };
    stream.on('error', fail);
    doc.on('error', fail);
    stream.on('finish', () => {
      if (settled) return;
      settled = true;
      resolve(outputPath);
    });

    doc.pipe(stream);

    // Global glyph sanitizer: PDFKit's built-in WinAnsi Helvetica has no glyph
    // for U+2212, en/em dashes, smart quotes, ellipsis, ₹, ≥, etc. — they render
    // as blank boxes (a "−" shows as a stray double-quote). Route EVERY drawn
    // string and its layout measurement through asciiSafe so both agree, catching
    // table cells, headings, paragraphs, cover, footers, and the '—' fallbacks
    // that bypass the per-field asciiSafe() calls.
    const drawText = doc.text.bind(doc);
    doc.text = (str, ...rest) => drawText(asciiSafe(str), ...rest);
    const measureHeight = doc.heightOfString.bind(doc);
    doc.heightOfString = (str, ...rest) => measureHeight(asciiSafe(str), ...rest);

    try {
      // 1. Cover (current first page). Headline money figure is the Layer-1
      // victim loss (the actual amount stolen); the all-layers trail-disputed
      // figure re-counts the same money across hops and is shown beneath it.
      renderCover(doc, {
        ackNo: String(ackNo),
        generatedStr: formatDate(new Date().toISOString()),
        victimLoss: summary.victim_loss_amount
          ?? summary.total_disputed_amount ?? report.total_disputed_amount,
        trailDisputed: summary.total_trail_disputed
          ?? summary.total_disputed_amount ?? report.total_disputed_amount,
        totalTxns: summary.total_transactions ?? report.total_transactions,
        totalLayers: summary.total_layers ?? report.total_layers,
        fraudStart: formatDate(summary.fraud_start_date ?? report.fraud_start_date),
        provenance,
      });

      // ── Front matter ──────────────────────────────────────────────────
      doc.addPage(); renderExecutiveSummary(doc, analysis, liens);
      doc.addPage(); renderVisualSummary(doc, charts);
      doc.addPage(); renderRoadmap(doc, analysis.investigation_roadmap || []);
      doc.addPage(); renderFindings(doc, analysis.key_findings || []);

      // ── Annexure (bulky tables, behind a divider page) ─────────────────
      doc.addPage(); renderAnnexureDivider(doc);
      doc.addPage(); renderLayers(doc, layerRows, analysis.reconciliation);
      doc.addPage(); renderMoneyFlow(doc, analysis.money_flow_network || {}, analysis.aggregators || []);
      doc.addPage(); renderCircularFlows(doc, analysis.circular_flows || []);
      doc.addPage(); renderMules(doc, analysis.mule_detection || []);
      doc.addPage(); renderLien(doc, liens);
      doc.addPage(); renderCashout(doc, cashoutView, { atmTerminals, recon: cashoutRecon });
      doc.addPage(); renderGeography(doc, geoView, posMerchants);
      doc.addPage(); renderTimeline(doc, analysis.timeline || [], analysis.reconciliation, analysis.day_of_week);
      // Annexure H — bank-attribution data-quality review (adds its own page).
      // Includes the parser self-healing audit (fuzzy matches / degraded columns).
      renderDataQuality(doc, analysis.data_quality || [], analysis.old_transactions || [],
        analysis.parse_warnings || []);

      // Draft emails (adds its own pages). Pass the full analysis so renderEmails
      // can derive the wallet/masked non-actionable sections and the per-letter
      // "verify bank" reviewer note (freeze-target set).
      renderEmails(doc, emails, analysis);

      // Footer + page numbers + per-page source hash across every buffered page.
      stampFooters(doc, provenance);
    } catch (err) {
      fail(err);
      return;
    }

    doc.end();
  });
}

// ─── Exports ─────────────────────────────────────────────────────────

module.exports = {
  generateReportPdf,
  // Exposed for unit tests; not part of the stable contract.
  _internals: Object.freeze({
    formatMoney,
    formatCount,
    formatDate,
    maskAccount,
    cashedOutForDisplay,
  }),
};
